### ISSUE TITLE
demoui进入edits模块后快速点击一个输入框，退出到主菜单后键盘不会销毁

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#104]
3.31最新版本的awtk，demoui进入edits后
快速点击其中一个输入框，让系统弹出软键盘
然后退出到主菜单，发现键盘一直不消失

**Comment by xianjimli** [comment]
已修改。谢谢

**Comment by soyzhc** [comment]
问题还是存在

**Comment by soyzhc** [comment]
6c04b95966dc4abc3b89e7efe1eb954e81b9369b
