### ISSUE TITLE
window_animator_slide_xxxx.c中结构体size成员初始化值错误

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#106]
比如 .size=sizeof(window_animator_t)
应该改为 .size=sizeof(window_animator_slide_t)
否则后续的malloc只会分配window_animator_t大小的对象，但却访问了更大的window_animator_slide_t成员，导致访问越界崩溃

window_animator_slide_down.c
window_animator_slide_left.c
window_animator_slide_right.c
window_animator_slide_up.c
这几个文件都有这个问题

**Comment by xianjimli** [comment]
已修改。谢谢

**Comment by soyzhc** [comment]
a558a70
