### ISSUE TITLE
能不能增加一些调试手段的说明文档

### ISSUE THREAD

**Issue by zhanglu993** [zlgopen/awtk#11]
你好，能不能增加一些调试手段的说明文档？移植过程中发现内存不足，定义失误的一些错误，由于没有log，断言之类的调试手段很难定位问题点。

**Comment by xianjimli** [comment]
好，谢谢。我整理一下，大家来补充吧

**Comment by zhanglu993** [comment]
多谢回复，另外能不能增加各个模块内存和CPU消耗计算方法的文档？方便评估

**Comment by xianjimli** [comment]
好，这两天加上

**Comment by xianjimli** [comment]
增加了两个内存函数，可以查看内存情况：
void tk_mem_dump(void);
mem_stat_t tk_mem_stat(void);

**Comment by xianjimli** [comment]
内存需求评估指南: https://github.com/zlgopen/awtk/blob/master/docs/memory.md

**Comment by zhanglu993** [comment]
收到，非常感谢。
