### ISSUE TITLE
建议：Label加一个文本自适应控件大小的功能

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#110]
比如Label中的文本太长，超过控件宽度时，可以选择下面其中一种样式：
1、超出部分显示 ...
2、水平单向循环滚动
3、水平左右乒乓滚动
4、垂直分行循环滚动

**Comment by xianjimli** [comment]
计划开发一个独立的控件，就像HTML中的marquee控件一样，以免把label控件搞得太复杂。最近两周重点是优化和稳定，并发布1.1版本。新功能放到1.2里吧。
