### ISSUE TITLE
将AWTK移植到STM32f429igtx裸系统 项目缺少文件

### ISSUE THREAD

**Issue by phenixyf** [zlgopen/awtk#111]
你好，我下载https://github.com/zlgopen/awtk-stm32f429igtx-raw里的stm32f429裸系统移植项目，里面缺少demo_main.c, demo_ui_app.c, assets-1m.c文件，并且include设置里的awtk的src和3rd，也需要手工添加。
请问这些文件在哪里，谢谢！

**Comment by xianjimli** [comment]
谢谢，我看看。

**Comment by xianjimli** [comment]
我试了没问题。确认是一下是这样取的代码吗：

```
git clone https://github.com/zlgopen/awtk-stm32f429igtx-raw.git
cd awtk-stm32f429igtx-raw
git clone https://github.com/zlgopen/awtk.git
```

**Comment by phenixyf** [comment]
可以了，一开始是从github download的不是clone的。把移植例程和awtk源码放不同文件夹了。
谢谢！
另外请教一下，awtk有类似emWin在VS下的simulation吗？在没有硬件平台时，可以在VS上验证一些example，修改example的效果也可以模拟出来。
看了下https://github.com/zlgopen/awtk-examples里的示例，在哪个软件仿真平台上可以修改并演示这些example?
再次感谢!

**Comment by xianjimli** [comment]
在windows、linux和macos都可运行啊。看下README
