### ISSUE TITLE
建议guage控件的指针加入锚点功能

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#116]
已经改好一个版本，补丁代码由罗智明提供，

[guage_anchor.diff.txt](https://github.com/zlgopen/awtk/files/3164534/guage_anchor.diff.txt)

**Comment by xianjimli** [comment]
好，谢谢。

**Comment by soyzhc** [comment]
已经加入按比例设置锚点

[guage_pointer.diff.txt](https://github.com/zlgopen/awtk/files/3166096/guage_pointer.diff.txt)
