### ISSUE TITLE
text_selector控件滚动位置卡在中间的问题

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#119]
罗智明  15:30:14
text_selector组件，在组件外部按下鼠标，然后鼠标再滑过组件并离开组件，然后再弹起鼠标，会导致text_selector组件中的文字移动，然后我修改了一下text_selector组件的代码，然后把diff发给你

[text_selector.diff.txt](https://github.com/zlgopen/awtk/files/3190425/text_selector.diff.txt)

**Comment by xianjimli** [comment]
好的，谢谢

**Comment by xianjimli** [comment]
已合并，谢谢。
