### ISSUE TITLE
stm32f429需要移植文件系统吗

### ISSUE THREAD

**Issue by wcyingdream** [zlgopen/awtk#12]
stm32f429需要给SD卡移植文件系统吗，需要往SD卡里放文件吗，用你的stm32f429的程序，下到板子里一直处在loading的界面

**Comment by xianjimli** [comment]
不需要。不好意思，最近改动比较多，明天我试试。

**Comment by wcyingdream** [comment]
好的，李老师辛苦了，我用的是野火的429，驱动都是正常的，参照你的429例程移植的。像字体文件和图片文件之类的都是已经写在程序里的了，不需要再放到SD卡里了，是吧

**Comment by wcyingdream** [comment]
下了你的最新版，已经可以用了

**Comment by wcyingdream** [comment]
嗯，429只有1M  flash，可以把图片，字体啥的放到SD卡去加载
