### ISSUE TITLE
文档里提到assets_gen.bat工具在哪？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#120]
xml转为AWTK使用的.data 源码中tools目录下提供xml_to_ui.c文件

**Comment by xianjimli** [comment]
这里：https://github.com/zlgopen/awtk-examples/tree/master/Meter-Demo

**Comment by ytchw101** [comment]
按照文档中“2.2节生成资源文件”说明，将assets_gen.bat中AWTK_DIR改为awtk源码的相对目录 如:@set AWTK_DIR=../awtk   然后双击运行assets_gen.bat 闪退？ 第二步中 在cmd 下"运行下面命令"是什么命令？   具体怎么操作 还没搞懂。。。   有空望回复    感激不敬！

**Comment by tangMans** [comment]
【1】以https://github.com/zlgopen/awtk-examples/tree/master/Meter-Demo为例，将“将assets_gen.bat中AWTK_DIR改为awtk源码的相对目录” ，指定是Meter-Demo/assets_gen.bat这个文件，而不是Meter-Demo/res/assets_gen.bat
【2】“在cmd 下"运行下面命令"是什么命令”，指的是在终端切换到Meter-Demo目录，然后执行：assets_gen.bat脚本，直接双击Meter-Demo/assets_gen.bat该文件也是可以的
