### ISSUE TITLE
安装 libsndio-dev libgtk-3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#122]
sudo apt-get install scons libsndio-dev libgtk-3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev后，重启虚拟机，提示The system is running in low-graphics mode，无法进入图形界面。

**Comment by xianjimli** [comment]
Ubuntu 16有BUG，在虚拟机里经常出现low-graphics，我经常要快照/恢复快照。现在装了Ubuntu 19，目前还没出现low-graphics的情况，你可以试试。

**Comment by soyzhc** [comment]
由于安装的某些组件，与Ubuntu16的x11配置有冲突，要手动强制更新配置

步骤1：
        重启虚拟机，按ctrl + alt + F1 进入纯字符界面，输入账号和密码
步骤2：
        1：cd /etc/X11
        2：sudo cp xorg.conf.failsafe xorg.conf
        3：sudo reboot

**Comment by xianjimli** [comment]
好的，谢谢
