### ISSUE TITLE
window_create动态创建几个窗口，如何实现各个窗口相互切换界面

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#123]
window_create动态创建2个窗口，如何实现2个窗口相互切换界面？
 1.查看了pdf文档里面4.3节有个window_manager  但只是列了几个函数 具体怎么使用未知。  
 2.下载了awtk-c-demos例程，里面有个multi_windows.c例子 中 ：widget_on(wm, EVT_KEY_DOWN, on_key_back_or_back_to_home, wm); 这一句怎么响应 EVT_KEY_DOWN（我用的正点原子stm32f429igtx板子）

**Comment by xianjimli** [comment]
关闭当前窗口就返回前一个窗口：
```
static ret_t on_close(void* ctx, event_t* e) {
  widget_t* win = widget_get_window(WIDGET(ctx));
  (void)e;
  return window_close(win);
}
```

**Comment by ytchw101** [comment]
可以 谢谢！
