### ISSUE TITLE
关于widget_set_prop_str

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#127]
widget_set_prop_str的第三个参数每个属性该怎么输入，哪里有文档说明吗？比如我设置一个widget窗口动画属性为向下滑出widget_set_prop_str(win, WIDGET_PROP_ANIM_HINT, WINDOW_ANIMATOR_SLIDE_DOWN);   那如果去除这个属性，第三个参数是写""吗？ 还比如

**Comment by ytchw101** [comment]
设置X方向偏移    widget_set_prop_str(win, WIDGET_PROP_XOFFSET, “10”);  第三个参数填数字字符串吗？等等...

**Comment by soyzhc** [comment]
https://github.com/zlgopen/awtk/blob/master/docs/manual/widget_t.md#widget_t_widget_set_prop_str

也可以看一下demo里面的使用

**Comment by xianjimli** [comment]
设置整数属性建议用widget_set_prop_int
