### ISSUE TITLE
combo_box open_window has NULL point error

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#130]
<combo_box open_window="language" readonly="true" x="10" y="bottom:50" w="200" h="30" tr_text="english"/>
如果language的windows不存在，下面这个地方会出现指针错误
  if (combo_box->open_window) {
    win = window_open(combo_box->open_window);
     **widget_resize(win, widget->w, win->h);**
    widget_layout_children(win);
  } else {
    win = combo_box_create_popup(combo_box);
  }

**Comment by xianjimli** [comment]
已修改。谢谢
