### ISSUE TITLE
Control tab_button in scrollview with key can not sync scrollbar 

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#134]
用按键控制scrollview中的tab_button（tab_button_set_value），tab_button超出当前界面后，滚动条不能移动。
如果把tab_button设置为focusable，就可以了滚动了。
看代码widget_ensure_visible_in_scroll_view是在widget_set_as_key_target里面执行的，如果没有焦点，不接收按键，就不执行这个操作。

**Comment by xianjimli** [comment]
好的，谢谢，我看看。

**Comment by xianjimli** [comment]
改了， 你有空试试。

**Comment by poweel** [comment]
ok了
