### ISSUE TITLE
scroll_view should ignore the diable item

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#136]
scroll_view 里面的子项如果禁用了，还是会占用一个位置，children_layout=default和children_layout=list_view都有相同的问题

**Comment by xianjimli** [comment]
disable不应该影响布局。visible可以影响，我再加个ignore_invisible参数吧。

**Comment by xianjimli** [comment]
增加了布局参数：

https://github.com/zlgopen/awtk/blob/master/docs/children_layouter_default.md

https://github.com/zlgopen/awtk/blob/master/docs/children_layouter_list_view.md
