### ISSUE TITLE
AWTK-port 中问题咨询

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#137]
AWTK-port 中platform.c  的 
 #define MEM2_MAX_SIZE 8 * 1024 * 1024
#define MEM2_ADDR (uint8_t*)0X81200000 + 5 * 1024 * 1024

ret_t platform_prepare(void) {
  tk_mem_init(MEM2_ADDR, MEM2_MAX_SIZE);
	
  return RET_OK;
}

这么分配8M内存是做什么用的？  一般分配多大比较合适？？

**Comment by xianjimli** [comment]
请参考这个文档：https://github.com/zlgopen/awtk/blob/master/docs/hardware_req.md

内存主要需求是：framebuffer、窗口动画和解码后的图片。

**Comment by xianjimli** [comment]
如果有系统的malloc，请使用系统的malloc。

**Comment by soyzhc** [comment]
tk_mem_init 是awtk自身管理的Heap，用于无malloc的裸系统
如果系统本身提供了标准malloc功能，则无需调用tk_mem_init初始化，
awtk_config.h 定义一个宏即可
#define HAS_STD_MALLOC 1

**Comment by ytchw101** [comment]
哦  谢谢
