### ISSUE TITLE
字体大小

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#139]
awtk中加载了完整的default.ttf资源      用widget_set_text显示中文， 那么字体大小该怎么改？试了lcd_set_font_size不行

**Comment by xianjimli** [comment]
在控件的style中设置: https://github.com/zlgopen/awtk/blob/master/docs/theme.md

**Comment by ytchw101** [comment]
哦  谢谢！ 以为能动态设置

**Comment by xianjimli** [comment]
新加了inline style，你可以试试：https://github.com/zlgopen/awtk/blob/master/docs/theme.md

```
widget_set_style_int(b, "font_size", 24);
```
