### ISSUE TITLE
imagegen 编译资源报错

### ISSUE THREAD

**Issue by zhanglu993** [zlgopen/awtk#14]
更新到最新版本imagegen后发现编译报错，具体如下：
(base) F:\sourcecode\awtk\original\awtk_new>F:\sourcecode\awtk\original\awtk_new\bin\imagegen.exe F:\sourcecode\awtk\original\awtk_new\demos\assets\raw\images\x1\anib.png F:\sourcecode\awtk\original\awtk_new\demos\assets\inc\images\anib.data bgra|bgr565
'bgr565' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

将bgra|bgr565改成bgra+bgr565后可以正常编译
(base) F:\sourcecode\awtk\original\awtk_new>F:\sourcecode\awtk\original\awtk_new\bin\imagegen.exe F:\sourcecode\awtk\original\awtk_new\demos\assets\raw\images\x1\anib.png F:\sourcecode\awtk\original\awtk_new\demos\assets\inc\images\anib.data bgra+bgr565
done

**Comment by xianjimli** [comment]
已修改，谢谢:)

**Comment by zhanglu993** [comment]
问题已解决
