### ISSUE TITLE
stb支持ttf字体

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#140]
现在系统用stb方式加载.ttf字体，那么程序中怎么获得任意大小字体的字模数据  比如  汉字：“好” 字体大小：32       查看font.h中有font_get_glyph函数 里是调用参数 font* f 的get_glyph 不知怎么弄 。、
在font_loader_stb中有个静态函数 font_stb_get_glyph 的第一个参数font_t* f  该怎么指定啊？？？

**Comment by xianjimli** [comment]
不需要调这么低级的函数，在style里指定字体的大小即可。

**Comment by ytchw101** [comment]
style指定 我知道        我主要是要动态的获得 某个字符 字模数据   这该咋弄呢？    我之前做好的是用freetype解析ttf字库 （都是在上位机软件里做的 ） 设置字体大小 调用FT_Load_Char即可解析 获得字模数据     awtk不知道咋用  这个font_stb_get_glyph 函数不知道咋用,第一个参数font* f咋填

**Comment by xianjimli** [comment]
请参考：canvas.c
