### ISSUE TITLE
freetype 支持truetype字体

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#141]
用freetype支持Truetype字体，定义了宏 #define WITH_FT_FONT   1     在font_loader_ft.c中USE_SYSTEM_FREETYPE  这个宏如果定义的话  是还需要自己添加freetype源码到工程吗 包括下面头文件
#include <ft2build.h>
#include <freetype/freetype.h>
#include <freetype/ftglyph.h>
#include <freetype/ftpfr.h>
#include <freetype/ftadvanc.h>

**Comment by xianjimli** [comment]
用这个就好了：3rd/freetype_single_header/freetype.h

如果启用USE_SYSTEM_FREETYPE，你得自己编译freetype，那是非常麻烦的事情。
