### ISSUE TITLE
EVT_DRAG事件问题咨询

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#147]
EVT_DRAG事件目前只是用在scrollbar中嘛？   我现在要实现某个控件（比如Label）可拖动 ，注册控件的EVT_POINTER_MOVE事件然后在里面根据坐标调用 widget_move 这样操作的....    

使用平台：arm+触摸屏

**Comment by xianjimli** [comment]
这个目前要自己处理。
