### ISSUE TITLE
wchar_t* 和char*转换

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#150]
wchar_t* 和char*转换   是用utf8_from_utf16  和 utf8_to_utf16 吧 /?

例:
       wchar_t* text=L"asxswq";
	char* pstr = NULL;
	pstr = utf8_from_utf16(text, pstr, wcslen(text));

这样写不对吗.!? 每次 返回pstr都为NULL     ？

**Comment by xianjimli** [comment]
```
str_t str;
str_init(&str, 0);
str_from_wstr(&str, text);
....
str_reset(&str);
```

**Comment by soyzhc** [comment]
utf8_from_utf16 也是可以的，你的输入参数有问题，可以看看代码的实现
