### ISSUE TITLE
动态改变屏保时间问题

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#151]
window_manager_set_screen_saver_time  不能动态改变屏保时间嘛?     比如程序一开始设置屏保3分钟  ，中途我想改为1分钟 。。。。。。

**Comment by xianjimli** [comment]
应该可以啊。

**Comment by ytchw101** [comment]
开机设置屏保如下：
wm_screensaver = window_manager();
  /*enable screen saver*/
  window_manager_set_screen_saver_time(wm_screensaver, 10*1000); //10s
  widget_on(wm_screensaver, EVT_SCREEN_SAVER, on_screen_saver, NULL);

10s后正常进入屏保

在另外一个地方（比如点击个按钮）修改屏保时间：
  window_manager_set_screen_saver_time(wm_screensaver, 1*1000); //1s
等好久没反应嘛？

平台（嵌入式ARM）

**Comment by xianjimli** [comment]
有个BUG，我修改了，你有空试试。

**Comment by ytchw101** [comment]
好 谢谢 ！  试了 可以了
