### ISSUE TITLE
编辑器输入法弹不出来

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#153]
一个界面创建了一个edit控件并设置其获得焦点edit_set_focus(edit, TRUE);  此时键盘可正常弹出，关闭键盘点击edit控件键盘也可正常弹出。。 我目的是只要进入有edit的界面都让其获得焦点然后自动弹出输入键盘 ，但是好像多次edit_set_focus之后，  关闭 了这个界面后再次打开后 键盘怎么都出不来，其他有edit控件的界面也一样  不知道什么原因》？

**Comment by xianjimli** [comment]
我需要一个最小重现问题的环境。
