### ISSUE TITLE
请教输入法问题？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#159]
在工程中更新了awtk源码后(用的是2019/06/15那个版本)，输入法切换到中文输入时，拼音汉字出来后 点击出来的字  界面就直接卡死了！！？   然后用之前的旧awtk与源码版本 输入汉字没问题。。。是什么问题（查看了下之前版本中文件日期大概是2019/05/07） 

平台是嵌入式ARM  字体采用stb方式加载

**Comment by ytchw101** [comment]
现在可以了 估计是我这边移植问题

**Comment by ytchw101** [comment]
现在有个新的问题就是 更新了最新的源码(2019/06/26)    window_manager_set_screen_saver_time(wm_screensaver, 300*1000); //5分钟
设置屏保时间不准了  大概几秒后就进入屏保。

**Comment by xianjimli** [comment]
demoui没有重现，是不是其它地方设置了。

**Comment by ytchw101** [comment]
程序没动  只是更新了最新的源码  烧写之前的程序基本是按照设置的5分钟时间进入屏保 ， 现在是几秒钟   不知道什么问题 ！

**Comment by ytchw101** [comment]
我再查一遍吧  按说不应该。。。。
