### ISSUE TITLE
希望主题Theme和样式Style可以动态创建，动态绑定到控件

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#16]
目前Theme和Style只能预先在xml里面描述好，在程序Init的时候加载到管理器
但程序运行中途无法动态增加新的样式，或修改样式，并立即应用到Widget上

这样在某些情况下使用不够方便，比如根据用户选择的颜色，动态修改一个Widget的背景色

**Comment by xianjimli** [comment]
好，谢谢，近期加上。

**Comment by ytchw101** [comment]
这个动态创建Style  
实现了吗？

**Comment by xianjimli** [comment]
加了，目前只是给IDE用的。
