### ISSUE TITLE
3rd/gpinyin中是否可以去掉对tkc模块中文件的引用

### ISSUE THREAD

**Issue by oskycar** [zlgopen/awtk#164]
3rd/gpinyin模块的file.h中包含了awtk/src目录下的tkc模块的头文件，但是gpyin模块中并没有用到，是否可以去掉的呢？

**Comment by xianjimli** [comment]
目前的做法确实很丑陋。

主要原因是，在没有文件系统时，要模拟一个文件系统API给gpinyin。

我再想想怎么改进一下。

谢谢建议。
