### ISSUE TITLE
common/utils.c 编译报错

### ISSUE THREAD

**Issue by oskycar** [zlgopen/awtk#165]
在mac平台使用clang编译时提示如下错误：
`tools/common/utils.c:63:10: error: cannot initialize return
      object of type 'char *' with an rvalue of type 'void *'
  return file_read(file_name, length);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~`

把utils.c63行改为：`return (char*)file_read(file_name, length);` 后编译通过，但不知是否正确。

**Comment by xianjimli** [comment]
可以。已修改，非常感谢。
