### ISSUE TITLE
使用cmake clang编译出来的库要小的多

### ISSUE THREAD

**Issue by oskycar** [zlgopen/awtk#166]
试着用cmake +clang编译了下，编译成功了，对应的demo可执行程序也编译出来了，运行正常。和scons编译出来的库相比小了不少。是因为scons用的gcc原因吗，还是默认编译的debug版本库。

cmakebuild目录中是用cmake+clang编译的，lib目录是用scons编译出来的。

![屏幕快照 2019-07-03 21 31 24](https://user-images.githubusercontent.com/771721/60595678-0beca400-9dda-11e9-96ce-e60ee975907f.png)

**Comment by xianjimli** [comment]
应该是-g的原因。如果加-Os，再strip，大小应该差不多。用-Os，再strip，arm gcc生成的libawtk.a大约700K。
