### ISSUE TITLE
字节转换请教

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#170]
wchar_t* text = L"123文档";
	str_t str;
	str_init(&str, 0);
	str_from_wstr(&str, text);
	rt_kprintf("size=%d,capacity=%d, str:%s\r\n",str.size,str.capacity,str.str);
	str_reset(&str); 
        
     为什么打印str.str字符串 123能显示, 汉字显示是乱码？ 是转换的有问题吗？
      str.size得到是9,  不应该和strlen("123文档") = 7 一样吗？

**Comment by xianjimli** [comment]
乱码的原因可能是终端的字符编码不是UTF8的。
