### ISSUE TITLE
新人，关于编译的示例其他系统运行问题

### ISSUE THREAD

**Issue by HaoQinLandv** [zlgopen/awtk#174]
编译的机器上运行没有问题，编译机器win10x64
![image](https://user-images.githubusercontent.com/24872385/61058199-5947c180-a429-11e9-96d3-8597149ccbb9.png)

运行测试机器，win7x64
![image](https://user-images.githubusercontent.com/24872385/61058168-4d5bff80-a429-11e9-8905-32411f00bed5.png)
朋友机器测试，win7x64
![image](https://user-images.githubusercontent.com/24872385/61058343-a035b700-a429-11e9-8627-d9d5be753fb1.png)

python gcc mingw64  c++ 环境均有,测试机器运行要么报错，要么白屏。
还请作者答疑，谢谢。

**Comment by soyzhc** [comment]
把资源文件夹也一起拷贝到运行机看看
目录结构：
```
demo/
  |-- demos/assets/
  |-- bin/demoui.exe
```
如果还不行，则修改 awtk_config.py，启用AGGE模式，去掉下面代码行的注释，再编译一次
```
NANOVG_BACKEND='AGGE'
```
