### ISSUE TITLE
scroll_bar 显示问题

### ISSUE THREAD

**Issue by linany** [zlgopen/awtk#175]
scroll_bar_d 的上下按钮是这里create的时候确定大小的，但是如果scroll_bar_d设置的是self_layout,在create的时候就不会有大小，这时候方向按钮就会一直没有大小，能不能在确定大小后再设置子按钮的大小

**Comment by xianjimli** [comment]
好的，下午我看看。

**Comment by xianjimli** [comment]
改了，你有空试试。谢谢。
