### ISSUE TITLE
移植awtk里面有一些头文件找不到

### ISSUE THREAD

**Issue by Jun1172** [zlgopen/awtk#178]
您好：
     移植awtk到新的平台，参考：https://github.com/zlgopen/awtk/blob/master/docs/porting_common.md
     里面的“ 三、要加入到工程的文件”
     发现存在找不到的头文件，如：aw_stat.h/aw_unistd.h/aw_dirent.h
     对比ST的工程，发现里面没有使用这类头文件。
     
     请问这些是在其他平台移植的时候也必须要有的么？例如ST的芯片。
     我可以到什么地方获取这些头文件？

     我尝试将这些找不到的头文件屏蔽，但是会导致大量的错误。

**Comment by xianjimli** [comment]
这些是AWorks OS的头文件，AWTK不会直接依赖。移植到ST，请参考：

https://github.com/zlgopen/awtk-stm32f103ze-raw

https://github.com/zlgopen/awtk-stm32f429igtx-raw

https://github.com/zlgopen/awtk-stm32f767igtx-raw
