### ISSUE TITLE
slist_remove

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#179]
slist_t slist;
        slist_init(&slist, destroy, slist_compare);
	char* ptext1 = "123";
       char* ptext2= "123";
	
	slist_append(&slist, ptext1);

**Comment by ytchw101** [comment]
slist_append(&slist, ptext2);

slist_remove(&slist,     这个怎么用 ？   有没有最好提供每个元素对应一个索引号  删除也根据索引来删除

**Comment by xianjimli** [comment]
用darray吧。
