### ISSUE TITLE
QR_code

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#183]
创建一个QRCode
 widget_t *new_qr_code = qr_create(cont_obj, 20, 20, 80, 80);
  qr_set_pixsize(new_qr_code, 2);
  qr_set_text(new_qr_code, "123456");
  widget_set_name(new_qr_code, "new_qr_code");
  widget_use_style(new_qr_code, "qr_border");

  widget_set_enable(new_qr_code, TRUE);
	qr_t* qr = QR(new_qr_code);
	
rt_kprintf("pixsize=%d, width=%d, %s, isvalid=%d, %ld\r\n", qr->pix_size,qr->qr_width, qr->qr_text,qr->isvalid,qr->qr_code_data); 
//为什么我把qr_on_paint_end中的QRcode_free注释掉, 返回的qr->qr_width 还是0  ,数据qr->qr_code_data为NULL   ？？      我该如何得到显示的二维码图片像素 数据。？

**Comment by xianjimli** [comment]
提到qrcode项目吧。
