### ISSUE TITLE
子控件处于焦点状态时，父控件focused	=1，但是state是normal

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#185]
我想实现子控件被选中后，父控件也改变一下背景，调试时发现：子控件处于焦点状态时，父控件focused=1，但是state是normal，所以没有办法通style修改父控件背景。
我这个需求还有其他方法实现吗？

**Comment by xianjimli** [comment]
父控件加属性focusable="true"，在focused=1时，才会启用FOCUS状态的style。

**Comment by poweel** [comment]
如果父控件加属性focusable="true"，那么在用按键切换焦点的时候，会在父控件停留吗？我只是想修改下父控件的背景，不想让父控件停留焦点。
场景是这样的，在一个lcd菜单里面，每一行是一个参数，左边是lable，右边是输入值的输入框，通过按键切换到每一行的输入框的焦点，选中这个输入框的时候，整行的背景都变化一下。

**Comment by xianjimli** [comment]
没想到更好的办法，增加了with\_focus\_state属性。你用with\_focus\_state="true"试试吧。
