### ISSUE TITLE
定时时间问题

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#186]
1.之前更新了（2019/06/15版本）源码后可以动态修改屏保时间了,时间也是准的。比如设置1分钟进入屏保，基本是就是一分钟。  现在又更新最新源码 屏保时间不对了， 设置5分钟估计几秒就进入屏保。
2. 在使用timer_add(my_on_timer, NULL, 2000);  设置2秒进入定时器，但是时间也不对变的很快。

**Comment by xianjimli** [comment]
我在MacOS上是正常的。
