### ISSUE TITLE
按钮注册EVT_LONG_PRESS事件无响应

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#187]
如题

**Comment by xianjimli** [comment]
增加属性 enable_long_press="true"

**Comment by ytchw101** [comment]
你好，我试了下， 长按会触发一次，  但我想怎样实现长按按钮不松手的话一直触发一个事件呢 ？而不是长按只触发一次 然后按钮就回弹。。。

**Comment by xianjimli** [comment]
这个你可以注册EVT_CLICK事件，并设置repeat参数。
