### ISSUE TITLE
定义WITH_BITMAP_FONT后编译错误

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#189]
在awtk_config.py里面把-DWITH_STB_FONT修改为-DWITH_BITMAP_FONT，fontgen编译会出错。
如果先用原始代码，编译出fontgen，然后去掉fontgen的编译，修改宏定义为WITH_BITMAP_FONT，编译通过后，demoui不能显示文字。
要用bitmap font还需要做其他设置吗？

**Comment by xianjimli** [comment]
目前OpenGL不支持位图字体，你可以选择CAIRO，修改awtk_config.py:

```
VGCANVAS='NANOVG'
```

**Comment by poweel** [comment]
freetype库可以支持FT_LOAD_TARGET_MONO这个渲染选项，去掉抗锯齿，渲染出单色位图。

**Comment by xianjimli** [comment]
不错！
