### ISSUE TITLE
scroll_bar设置fg_color不生效，bg_color，border_color都可以生效

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#195]
scroll_bar_m设置fg_color不生效，bg_color，border_color都可以生效，追踪代码发现scroll_bar_mobile_on_paint_self里面style_get_color没有获取到正确的值。

还有一个问题是scroll_bar_d没有这个绘制函数，scroll_bar_d是在什么地方获取前景色，背景色的呢?

下面是我的style设置
<scroll_bar_m>
    <style name="default" border_color="#000000" bg_color="#ff00ff" fg_color="#00ff00">
        <normal />
        <over />
        <pressed />
    </style>
</scroll_bar_m>

**Comment by xianjimli** [comment]
style中间要将状态。如：
```
<scroll_bar_m>
<style name="default" border_color="#000000" bg_color="#ff00ff" fg_color="#00ff00">
<normal />
</style>
</scroll_bar_m>
```

**Comment by xianjimli** [comment]
scroll_bar_d要设置其子控件dagger的style。

**Comment by poweel** [comment]
已经ok了，多谢！
