### ISSUE TITLE
mledit输入键盘展开问题

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#197]
我是这样：一个界面创建了个mledit控件，并设置焦点mledit_set_focus这样键盘自动展开。当我隐藏该界面(不是close)显示另一个界面， 再从另一个界面返回本界面显示后， 如何能让键盘再自动展开 有什么方法？  试了好些方法没成功

**Comment by xianjimli** [comment]
在窗口的EVT_WINDOW_TO_FOREGROUND事件中调用mledit_set_focus试试。

**Comment by ytchw101** [comment]
这个方式试过了，会导致键盘出不来 然后点击也出不来    并且导致其他界面的带有edit的 键盘都不会弹出

**Comment by ytchw101** [comment]
现在给edit加了个 EVT_PAINT_DONE 事件 ，在这里mledit_set_focus可以  ,  在EVT_WINDOW_TO_FOREGROUND中设置个标识(bFlag)  这样EVT_PAINT_DONE中判断然后mledit_set_focus只设置一次即可    （但觉得理论上应该是在EVT_WINDOW_TO_FOREGROUND就应该可以 
 。。。。）

**Comment by xianjimli** [comment]
原因是弹出/关闭软键盘时也触发了这两个事件。最新代码已经改了，你可以参考这个例子：

https://github.com/zlgopen/awtk-c-demos/blob/master/demos/mledit_auto_focus.c

**Comment by ytchw101** [comment]
可以 谢谢
