### ISSUE TITLE
mledit 输入法类型

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#198]
mledit没有提供设置输入键盘类型接口，我用edit控件的edit_set_input_type  设置类型为edit_set_input_type(edit, INPUT_EMAIL);  类型无反应   还是中/英文都有。。。 

mledit_set_focus也没有... 但使用edit_set_focus是可以的

**Comment by xianjimli** [comment]
mledit不支持输入类型，其它GUI好像也不支持。为什么需要输入类型？

**Comment by xianjimli** [comment]
增加了mledit_set_focus，你有空试试。

**Comment by ytchw101** [comment]
因为比如输入一些条形码字符（是ascii码）或者邮件名等不需要中文地方

**Comment by xianjimli** [comment]
为什么不用edit呢

**Comment by ytchw101** [comment]
因为edit不能换行  ，我如果设置控件长度是固定的且是正方形，字符较多时不能换行，

**Comment by xianjimli** [comment]
mledit目前支持切换键盘，但是不对内容进行限制。

```
widget_set_prop_int(widget, WIDGET_PROP_INPUT_TYPE,INPUT_EMAIL)
```

**Comment by ytchw101** [comment]
哦  好
