### ISSUE TITLE
如何横屏/竖屏

### ISSUE THREAD

**Issue by kuangdazzidd** [zlgopen/awtk#2]
请问哪个接口可以实现屏幕显示的横屏竖屏切换啊

**Comment by xianjimli** [comment]
非常好的问题，目前还不支持，最近会加上。谢谢

**Comment by kuangdazzidd** [comment]
好的，谢谢

**Comment by xianjimli** [comment]
请参考：https://github.com/zlgopen/awtk/blob/master/docs/lcd_rotation.md

**Comment by kuangdazzidd** [comment]
谢谢，已更新测试可以使用，持续关注中！
