### ISSUE TITLE
edit 光标刷新 问题咨询

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#200]
我界面左边一个区域用来显示二维码，右边是个mledit 控件,  当输入文字后更新左边二维码显示, 发现当我不输入的时候只有光标在闪烁， 但同时为什么 二维码显示区域也一直在重绘（注:我给二维码显示区域注册了EVT_PAINT用来观察）    这样的结果是 当我输入的文字越来越多时 界面越来越卡   。。应该是一直重绘二维码导致的

**Comment by xianjimli** [comment]
界面上只要有一个控件需要重绘，所有控件的绘制流程都会走，但是不在脏矩形内的部分会被裁剪掉。

二维码是自己做的还是用的awtk-qr？

**Comment by ytchw101** [comment]
使用的   awtk-qr

**Comment by ytchw101** [comment]
那有木有好的解决方法呢？

**Comment by xianjimli** [comment]
缓存awtk-qr到图片，不要每次绘制都生成。
