### ISSUE TITLE
求教：更新最新代码不显示

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#202]
平台：嵌入式ARM+RTT+LCD(480*272)
问题描述：
更新最新源码（19/08/10版本）后我的lcd屏不显示（花屏），每次更新源码我都是替换掉旧的src和3rd文件夹的所有源码，其他配置和代码不作任何改动。 更新最新源码工程中需添加以下文件
新添加以下文件:
src/window_manager/window_manager_default.c
src/native_window/native_window_raw.c
src/widgets/dialog_helper.c
src/base/native_window.c 
添加完成后，编译通过，烧写到板子后lcd不显示（只是雪花屏），烧以前程序是没问题的。
试了2、3次还是如此，目前还在找原因。。。，不知道更新最新源码，还有啥要特殊配置吗！！ 
望回复，感激不尽！

**Comment by xianjimli** [comment]
你先用1.2。过几天我回公司了，在STM32F429上试试，目前我手上没板子，测试不了。

**Comment by ytchw101** [comment]
好的  幸苦了...

**Comment by xianjimli** [comment]
改了一个native window初始化顺序的bug，你更新代码试试。

**Comment by ytchw101** [comment]
可以了 谢谢！

**Comment by ytchw101** [comment]
可以了 谢谢！
