### ISSUE TITLE
edit控件注册焦点事件处理，不能获取第一次焦点事件

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#203]
有一个窗口，第一个控件是一个edit控件，我想在这个控件获得焦点的时候做一些自定义处理，目前发现一个问题是：控件在第一次获得焦点的时候，还没有注册焦点处理事件，我用断点跟踪，先执行了window_open操作，然后执行了edit_on_event里面的EVT_FOCUS事件处理，最后执行了init_children_widget这个操作，怎么才能提前给这个edit控件注册处理函数呢？

widget_t* win = window_open("phonebook_addgroup");
if (win) {
  init_children_widget(win);
}

**Comment by xianjimli** [comment]
我在widget factory中增加了创建widget后触发EVT_WIDGET_FACTORY事件，应该可以达到你要的效果：

```
static ret_t on_widget_created(void* ctx, event_t* e) {
  widget_t* widget = WIDGET(e->target);
  widget_t* win = widget_get_window(widget);

  log_debug("%s widget %s created\n", win->name, widget_get_type(widget));

  return RET_OK;
}


ret_t application_init() {
  widget_t* win = NULL;
  emitter_t* emitter = EMITTER(widget_factory());
  uint32_t id = emitter_on(emitter, EVT_WIDGET_CREATED, on_widget_created, NULL);

  win = window_open("basic");
  
  emitter_off(emitter, id);

  return RET_OK;
}
```
