### ISSUE TITLE
每个控件最多可以设置多少个属性？

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#204]
我设置一个edit控件，增加了一些自定义的属性，结果这个控件的位置就显示不对了。经过检查发现，如果控件的属性超过12个，就会出错。有没有宏定义设置这个最大值？

**Comment by xianjimli** [comment]
增加了宏TK_XML_MAX_ATTRS控制XML属性的个数(缺省为24)，需要重新生成资源，你有空试试。

谢谢。
