### ISSUE TITLE
问一下awtk是否支持圆形屏？

### ISSUE THREAD

**Issue by zzzh** [zlgopen/awtk#205]
如题

**Comment by xianjimli** [comment]
圆形屏和方形屏并无差别，只是PC模拟时盖一个圆形图片在上面。你可以参考一下我们做的只能手表demo：http://zlgawtk.bceapp.com/awtk/demos/SmartWatch-Demo/index.html

**Comment by zzzh** [comment]
谢谢，不知实现这样的效果对硬件有什么要求？

**Comment by xianjimli** [comment]
我们用的RT1052

**Comment by zzzh** [comment]
如果用CROTEX-M4芯片，不带2D加速，不知能否带得动？

**Comment by xianjimli** [comment]
看屏幕大小，200x200应该可以，400x400可能不行。

**Comment by zzzh** [comment]
多谢！
