### ISSUE TITLE
widget_dispatch_event_to_target_recursive:1354 widget != NULL && e != NULL

### ISSUE THREAD

**Issue by hongshuangzhu** [zlgopen/awtk#207]
使用slide_view的时候经常报上面的错误，导致效果不理想（时常获取不到按下事件，会产生移动时间）。
请教一下，这个是什么原因导致的呢？

**Comment by hongshuangzhu** [comment]
sleder_view首次运行时很容易出现，没有获取到点击事件，但是有drag响应

**Comment by hongshuangzhu** [comment]
是因为资源没有加载完影响的吗

**Comment by xianjimli** [comment]
怎么重现呢？

**Comment by hongshuangzhu** [comment]
我之前用1.1有这个问题，昨天升级到1.2，今天重新弄了下，已经没有这个问题了

**Comment by hongshuangzhu** [comment]
我之前用1.1有这个问题，昨天升级到1.2，今天重新弄了下，已经没有这个问题了
