### ISSUE TITLE
编译cairo和pixman存在config.h冲突问题

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#208]
这两个库都有同样名字的config.h文件，如果把这两个库都加入include路径
会导致pixman可能包含到cairo的config.h，导致编译失败

建议修改这两个第三方库的包含代码，使之更规范化，避免冲突
这里有我修改的一个补丁文件，但修改的文件有点多，仅作参考

[cairo_pixman_config_h.diff.txt](https://github.com/zlgopen/awtk/files/3500725/cairo_pixman_config_h.diff.txt)

**Comment by xianjimli** [comment]
已合并。谢谢。
