### ISSUE TITLE
黑白的PNG图片不能显示

### ISSUE THREAD

**Issue by zjm1060** [zlgopen/awtk#210]
https://www.easyicon.net/1176507-USB_icon.html
1.2版本的awtk不能显示上面所提供的PNG图片
报错内容
bitmap_init_from_rgba:311 bitmap != NULL && data != NULL && (comp == 3 || comp == 4)
image_on_paint_self:41 widget_load_image(widget, image_base->image, &bitmap) == RET_OK

**Comment by xianjimli** [comment]
最新代码支持了。谢谢
