### ISSUE TITLE
怎么给 Label 设置下划线  ?

### ISSUE THREAD

**Issue by V1ki** [zlgopen/awtk#214]
Label 有办法 设置下划线  , 如果不行的话,有没有其他比较便捷的方法来设置下划线.

**Comment by V1ki** [comment]
找到方法了,可以将border 设置bottom 以设置下划线.

**Comment by V1ki** [comment]
虽然可以使用border 来设置下划线,但是只有border 在不停的闪烁,请问 border的实现原理是什么?

**Comment by xianjimli** [comment]
什么平台？我在Linux上测试没问题。

**Comment by V1ki** [comment]
> 什么平台？我在Linux上测试没问题。

海思的HiFB

**Comment by xianjimli** [comment]
border没有什么特殊的啊。

**Comment by V1ki** [comment]
> border没有什么特殊的啊。

感觉有可能是因为border的高度太低了,有办法设置border的高度吗?

**Comment by xianjimli** [comment]
你修改一下这行代码试试：

widget.c:1083         canvas_draw_hline(c, 0, h - 1, w);

**Comment by V1ki** [comment]
> canvas_draw_hline(c, 0, h - 1, w);

canvas_draw_hline 这个方法好像并不能直接设置hline 的高度,我把这个地方该成fill_rect 试试.

**Comment by xianjimli** [comment]
你的高度指线宽还是y的坐标？

**Comment by V1ki** [comment]
> 你的高度指线宽还是y的坐标？

vgcanvas_set_line_width(canvas, 1);  
按照这个来说,应该是指线宽

**Comment by V1ki** [comment]
将之前绘制底部border的方法改成如下方法,并且在style 中设置 ``border_width``  为大一些的值,就不会出现非常严重的闪烁.

```
      if (border & BORDER_BOTTOM)
      {
        canvas_set_fill_color(c, bd);
        canvas_fill_rect(c, 0, h-border_width, w, border_width);
        // canvas_draw_hline(c, 0, h - 1, w);
      }
```
