### ISSUE TITLE
在嵌入式linux上运行CPU占用率很高

### ISSUE THREAD

**Issue by lzy2259** [zlgopen/awtk#216]
我把awtk移植到我们的开发板上，运行smartwatch那个demo发现就算什么都不操作CPU也有10%的消耗。CPU主频是1.2G A35.在慢慢滑动滑块菜单时感觉有点卡顿。请问cpu占用率和卡顿可以优化吗？

**Comment by xianjimli** [comment]
『不操作CPU也有10%的消耗。』这个是可以优化的，目前是每16ms唤醒一次，可以用select实现主循环，没有事件时就不唤醒。近期我会着手解决这个问题。

**Comment by xianjimli** [comment]
卡顿要看具体情况进行优化了，自己profile一下，找出热点进行优化。如果是ZLG的客户，可以联系技术支持协助。

**Comment by soyzhc** [comment]
建议下载最新的 awtk-linux-fb，我们最近优化了这个问题

**Comment by lzy2259** [comment]
验证了没有操作的时候CPU在1%以下。赞一个
