### ISSUE TITLE
gcc 编译时 new 重载与声明不符,导致编译失败的问题

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#221]
当没有定义 -DHAS_STD_MALLOC 时, 使用gcc编译会出现错误

主要是由于 new.cpp 中的 new 重载函数与 new.hpp 中的声明不一致
new.cpp 中的函数定义没有加 throw(std::bad_alloc) 导致

[mem_new.diff.log](https://github.com/zlgopen/awtk/files/3551504/mem_new.diff.log)

修改后 Windows 和 Linux 都能编译通过, Windows能正常运行
但Linux运行时会崩溃, 原因是在 mem.c 中 malloc 被重写了, 导致程序启动时, 
main 函数前的初始化代码调用了 malloc,  导致 malloc 先于 tk_mem_init 被调用

**Comment by xianjimli** [comment]
已合并，谢谢。
