### ISSUE TITLE
适配mingw时,有个测试用例编译失败

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#224]
* 主要原因是之前 bsvg 修改 float_t -> float 时导致的问题, svg_parse_numbers 函数原型与传入参数类型不匹配
* 还有一个问题是, 之前为了适配 mingw 修改 SConstruct 不够简洁, 现在发现一个更简洁的写法

具体修改见我上传的 diff

[awtk_mingw.diff.log](https://github.com/zlgopen/awtk/files/3563254/awtk_mingw.diff.log)

**Comment by xianjimli** [comment]
已合并，谢谢。
