### ISSUE TITLE
一个有edit控件的窗口进入后台后，edit控件没有触发失去焦点的事件

### ISSUE THREAD

**Issue by poweel** [zlgopen/awtk#227]
打开一个没有edit控件的新窗口，之前有edit控件的窗口（不可关闭）进入后台，进入后台的窗口里面的edit控件没有触发失去焦点的事件。

**Comment by poweel** [comment]
我们现在是用的1.2的分支，照着你的提交（set unfocused when window to background）做了类似的修改后，进入后台的窗口里面的edit控件还是没有失去焦点的事件。是master的窗口管理有较大修改，我需要合并最新代码吗？
我希望能做到进入后台的的窗口里面的控件能失去焦点，这个窗口回到前台后，焦点能够恢复到最后一个有焦点的控件上。

**Comment by poweel** [comment]
如果我在edit_request_input_method里面对窗口进入前台后后台的事件进行一个处理，是不是也可以？参考（widget_on(win, EVT_WINDOW_OPEN, edit_request_input_method_on_window_open, widget);）
因为我们的程序在其他地方有对窗口进入前后台的事件进行了处理，这两个地方的事件处理是不是只能保留一个？

**Comment by poweel** [comment]
我们还发现一个问题，就是在有edit框的窗口上打开一个对话框，有时候会出现，edit框会把对话框覆盖一部分，目前还没发现有什么规律。

**Comment by xianjimli** [comment]
最新代码比较稳定，你可以在最新代码上试试。
