### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#233]
点击按钮切换界面显示， 如果只在界面动态创建 2 、3 个控件(每个控件都有设置汉字文本)  反应比较快 ，如果创建7、8个控件(每个控件都有设置汉字文本) 感觉点击按钮后约等1-2秒才切换过去。 如果界面有要显示图片那切换更慢（先预加载图片会快不少）.....  查阅文档我把下面几个注释了还是控件一多反应有点慢， 不知道还有其他什么方法优化？？

1.怀疑字体渲染太慢? 让lcd_draw_glyph直接返回，看看效果如何。

2.怀疑图片渲染太慢? lcd_draw_image直接返回，看看效果如何。

3.怀疑填充颜色太慢? lcd_fill_rect直接返回，看看效果如何。

平台：嵌入式ARM(96MHz)  LCD (采用 2fb）

**Comment by xianjimli** [comment]
用的位图字体吗？

**Comment by ytchw101** [comment]
就是找的 .ttf字体转为.res加载到程序， 然后解析方式采用stb

**Comment by ytchw101** [comment]
可以了
