### ISSUE TITLE
编码转换

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#239]
如程序中定义：
	 wchar_t* ptext = L"单色";
	 char* text = "单色";

打印: ptext : 0x5355, 0x8272  (utf16编码)
         text :   0xb5a5, 0xc9ab  (gb2312编码)

awtk有没 gb2312和utf16的转换接口 ？

**Comment by xianjimli** [comment]
没有。使用UTF-8编码就行了，要翻译的字符串放到XML文件中去。
