### ISSUE TITLE
文档相关问题

### ISSUE THREAD

**Issue by jason-mao** [zlgopen/awtk#240]
awtk开发实践.pdf 5.3.5 `插值算法名称`， 在目录上面显示为 `插值算法吊称`.
<img width="218" alt="屏幕快照 2019-09-27 下午5 36 47" src="https://user-images.githubusercontent.com/25599977/65759527-bc561400-e14d-11e9-8dc6-62d83e2a6f89.png">

**Comment by jason-mao** [comment]
另外一个问题，https://github.com/zlgopen/awtk/blob/master/docs/docs/how_to_enable_key_touch_sound.md，
这个链接失效了

**Comment by xianjimli** [comment]
好的，谢谢。
第二个问题改了。第一个问题，我请同事看看。

**Comment by soyzhc** [comment]
请问你看的《AWTK开发实践》是哪个版本的呢？我这里看最新发布的V0.70是没有这个问题

https://github.com/zlgopen/awtk-docs

**Comment by jason-mao** [comment]
@soyzhc 我也是0.7的版本。电脑是MAC。

**Comment by soyzhc** [comment]
感谢提醒，确实在mac上有问题，近期会更新一版
