### ISSUE TITLE
关于移植层 get_time_ms 修改返回 uint64_t 引起的问题

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#241]
之前（2019.9.4）统一修改了移植层接口get_time_ms返回值由uint32_t 改为 uint64_t，
函数接口已经不兼容，建议将 get_time_ms 也修改名字为 get_time_ms64 （无需保留之前的get_time_ms）

原因是如果函数名保留之前的，编译链接都不会报错，但实际运行的时候会出现奇奇怪怪的问题，我们在使用过程中就碰到了坑，比如demoui的system bar 会莫名其妙的消失

再者，目前已经有一定量的用户在使用awtk，包括公司内部，碰到这个坑的几率很大，而且很难排查，因为这些问题现象一眼看过去根本不会想到是get_time_ms的问题

所以既然把接口协议改了，那就连同名字也一起改了，让问题能在编译时就暴露出来，避免后面再花费大量的时间调试

**Comment by xianjimli** [comment]
好的
