### ISSUE TITLE
xml文件成功创建了一个spin_box,点击spinbox的上下按键可以改变其值，我要怎么获取这个值？

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#242]

**Comment by YinWenshuo** [comment]
xml文件成功创建了一个spin_box,点击spinbox的上下按键可以改变其值，我在代码里面要怎么才能获取这个值？ 我要使用到这个值

**Comment by xianjimli** [comment]
edit是spin box的基类。调用edit的函数去获取值。你可以参考下面的文档和代码：

https://github.com/zlgopen/awtk/blob/master/docs/manual/spin_box_t.md

https://github.com/zlgopen/awtk-c-demos/blob/master/demos/spin_box.c

**Comment by YinWenshuo** [comment]
好了，回复好及时，非常感谢！
