### ISSUE TITLE
类似于windows菜单功能怎么做？

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#249]
类似于windows菜单功能怎么做？使用tab_control貌似做不到。

**Comment by xianjimli** [comment]
目前只支持一级菜单，放一排按钮。点击按钮时，打开菜单。

**Comment by YinWenshuo** [comment]
> 目前只支持一级菜单，放一排按钮。点击按钮时，打开菜单。

你说的是tab_control吗？我目前只要实现一级菜单就可以了。但是tab_control好像一定要默认一个active page？我想进入页面后，首先是一排按钮，pages不显示，然后用户点击某个按钮后就弹出对应的page。

**Comment by xianjimli** [comment]
没太明白，菜单不是弹出的吗？怎么会用tab control呢？

**Comment by YinWenshuo** [comment]
> 没太明白，菜单不是弹出的吗？怎么会用tab control呢？

那是用哪个控件？有没有demo？

**Comment by xianjimli** [comment]
demoui里有个context menu菜单。

**Comment by YinWenshuo** [comment]
好的，多谢回复。改天参考context menu demo，看看能不能实现我想要的功能。
