### ISSUE TITLE
关于 操作手册文档 有个“笔误”的地方

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#253]
下面这个操作手册文档是不是有误？
https://github.com/zlgopen/awtk/blob/master/docs/manual/gif_image_t.md

在xml中使用"gif_image"标签创建GIF图片控件。如：

<gif_image image="bee"/>

应该是这样：
<gif  image="bee"/>

要不然xml解析时会报错：
ui_builder_default_on_widget_start: not supported type gif_image
aps: src/ui_loader/ui_builder_default.c:43: ui_builder_default_on_widget_start: Assertion `!"not supported"' failed.
Aborted (core dumped)

**Comment by xianjimli** [comment]
已修改，谢谢。
