### ISSUE TITLE
小窗口可以拖拽移动位置吗？

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#255]
例如，awtk的MusicPlayer Demo，里面的Equalizer，Advance这样的弹出来的dialog，能不能做到摁住鼠标拖拽，改变其位置？？（应该是可以做到的吧，拖拽的时候，改变advance dialog的x、y坐标。如果awtk有实现的demo，我就懒得去琢磨了，比较没空。。。）

**Comment by xianjimli** [comment]
不急的话，等我下周来搞。

**Comment by YinWenshuo** [comment]
不急，有这个功能会更方便更有特色。

**Comment by xianjimli** [comment]
你参考这个文档：
https://github.com/zlgopen/awtk/blob/master/docs/manual/draggable_t.md

**Comment by YinWenshuo** [comment]
可以了，很好用，多谢！！！
