### ISSUE TITLE
win下运行正常,linux下出错

### ISSUE THREAD

**Issue by 21pages** [zlgopen/awtk#256]
<pre>app_root_is_valid:43 app_root != NULL
try /home/sun/learn/awtk/awtk
app_root=/home/sun/learn/awtk/awtk/demos
Init opengl done.
段错误 (核心已转储)
</pre>
vscode调试,发现是在
文件awtk/src/native_window/native_window_sdl.c里,
函数native_window_create_internal里,
调用glDisable(GL_STENCIL_TEST)死掉的

**Comment by xianjimli** [comment]
Linux什么版本，老版本OpenGL有问题。可以改用AGGE渲染(awtk_config.py)：

```
NANOVG_BACKEND='AGGE'
```

**Comment by 21pages** [comment]
改用agge可以了,谢谢
