### ISSUE TITLE
nanovg_agge对rgb565格式不支持导致界面显示异常，stm32f429 发生hardfault的错误

### ISSUE THREAD

**Issue by YasirLiang** [zlgopen/awtk#26]
你好!调试发现nanovg_agge对rgb565格式不支持，在函数执行断言后就出现了段错误！不过在pc上模拟是通过的。烧写到stm32f429igt6的调试过程如下面的图：

![1](https://user-images.githubusercontent.com/13192373/47758267-277b3a00-dca2-11e8-9edc-c6ccf7fff4fd.png)
![2](https://user-images.githubusercontent.com/13192373/47758270-2e09b180-dca2-11e8-96f8-82714bff3a20.png)
    Moltanisk 2018/10/30

**Comment by xianjimli** [comment]
麻烦确认一下，LCD是否用lcd_mem_bgr565_create_three_fb创建的。

请参考: https://github.com/zlgopen/awtk-stm32f429igtx-raw/blob/master/USER/main.c

**Comment by YasirLiang** [comment]
你好！不是，是用lcd_mem_rgb565_create_three_fb创建的，用的是例程里默认的lcd_mem_rgb565_create_three_fb不是lcd_mem_bgr565_create_three_fb

**Comment by xianjimli** [comment]
好的。后来为了统一命名方式(按各颜色通道的内存地址从低到高)，改了函数名。现在AWTK的接口基本稳定了，以后这类不兼容的改动比较少了。
