### ISSUE TITLE
控件使用问题

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#264]
1.text_selector 不能支持显示中文吗？
2.combo_box显示多项时，点击下拉框，框从上展开显示，有没办法向下展开?
   combo_box显示多项时,右侧滑块能否超过高度时，一直显示，因为触摸屏平台有时点击项上下滑动
   时，很难滑到想选的项再去选择。

**Comment by xianjimli** [comment]
1.我在PC上试了，可以显示中文。
2.没太明白你的意思。

**Comment by ytchw101** [comment]
2.就是比如创建combo_box 控件，并添加10个项，  LCD触摸屏是480*272 ， combo_box 控件下方空间还剩100高度，那么是显示不了10个项的，那么此时点击combo_box 下拉按钮， 实际效果是菜单向上展开，并显示控件上方空间高度能显示的最大项个数的最后几个项，  那么要选择其他项的话 ，那就只有滑动选择， 但是滑动选择感觉使用起来很困难(主要是感觉右侧的滑块不是固定的，而是点击项目区域时才自动出来)！！
