### ISSUE TITLE
lcd_reg.inc是否也可以支持draw_image_matrix函数？

### ISSUE THREAD

**Issue by zhanglu993** [zlgopen/awtk#27]
你好，lcd_reg.inc是否也可以支持draw_image_matrix函数？现在调用 Guang模式时发现 guage->pointer_image无法显示，跟踪代码发现
ret_t lcd_draw_image_matrix(lcd_t* lcd, draw_image_info_t* info) {
  return_value_if_fail(lcd != NULL && info != NULL, RET_BAD_PARAMS);
  if (lcd->draw_image_matrix != NULL) {
    return lcd->draw_image_matrix(lcd, info);
  }
  return RET_NOT_IMPL;
}
lcd->draw_image_matrix 在 lcd_reg.inc中是没有定义的

**Comment by xianjimli** [comment]
需要framebuffer才能支持。如果有内存作为显存(320x240需要150K)，STM32F103这类平台也是可以使用Framebuffer的，在lcd flush函数中把变化区域写到LCD即可。
