### ISSUE TITLE
定时器启动异常的问题

### ISSUE THREAD

**Issue by gaoyuan1111** [zlgopen/awtk#280]
我在添加定时器的时候遇到了定时器不工作的问题。打印为“User change time: 1766298524 => 1767191180”。我怀疑是get_time();获取到的时间出了点问题。所以我请教一下如何将定时器的时间判断改为系统运行时间。

**Comment by xianjimli** [comment]
什么平台

**Comment by gaoyuan1111** [comment]
linux

**Comment by xianjimli** [comment]
感觉有长时间操作阻碍了UI线程

**Comment by gaoyuan1111** [comment]
"有长时间操作"是什么意思？

**Comment by xianjimli** [comment]
1766298524 和 1767191180是两次循环的时间，正常情况下不会差别这么大

**Comment by gaoyuan1111** [comment]
这个循环时间跟系统时间无关吗？

**Comment by xianjimli** [comment]
你用的最新版本吗？记得改成与系统时间无关了

**Comment by gaoyuan1111** [comment]
2018/11/30

    增加一些测试代码。
    增加函数 widget_insert_child/widget_restack。
    用户修改系统时间后，更新定时器的启动时间，否则可能导致定时器长时间不会触发。
是这次修改吗？

**Comment by xianjimli** [comment]
2019/09/30

修改文档的 BUG（感谢俊杰提供补丁）。
edit/mledit 的 margin 从 style 中获取，从属性获取仍然保留（但不支持在 IDE 中设置）。
**使用 sokol 库中的函数获取时间。**
增加 event source。

**Comment by gaoyuan1111** [comment]
我去看一下 谢谢
