### ISSUE TITLE
焦点移动问题

### ISSUE THREAD

**Issue by cuimeng2213** [zlgopen/awtk#282]
目前修改代码之后焦点移动只支持前后移动。 如何能修改为支持上下左右移动呢？
`#ifndef TK_KEY_MOVE_FOCUS_NEXT
#define TK_KEY_MOVE_FOCUS_NEXT TK_KEY_DOWN
#endif /*TK_KEY_MOVE_FOCUS_NEXT*/

#ifndef TK_KEY_MOVE_FOCUS_PREV
#define TK_KEY_MOVE_FOCUS_PREV TK_KEY_UP
#endif /*TK_KEY_MOVE_FOCUS_PREV*/
`

![图片](https://user-images.githubusercontent.com/19948474/68933326-60b01a80-07cf-11ea-89ce-b900912dd653.png)

**Comment by xianjimli** [comment]
我还在思考这个问题。

**Comment by cuimeng2213** [comment]
我这有个思路， 可以根据移动方向计算可以聚焦的结点位置信息 返回最近的结点 然后设置该结点focused

**Comment by xianjimli** [comment]
目前实现了上下移动垂直焦点，左右键切换水平焦点：https://github.com/zlgopen/awtk/tree/rework-focus

**Comment by cuimeng2213** [comment]
好的 我更新代码试试。 你是这个开源代码的维护人员？

**Comment by cuimeng2213** [comment]
不好意思你那个提交被我给点错关闭了。。

**Comment by cuimeng2213** [comment]
功能已经实现

**Comment by xianjimli** [comment]
还测试一下，和软键盘结合起来，再合并到主分支。

**Comment by cuimeng2213** [comment]
![图片](https://user-images.githubusercontent.com/19948474/69032889-909e2e80-0a18-11ea-93bd-072629b13e84.png)
这样子写貌似会有问题，假如向右侧移动，右侧的焦点y轴与当前焦点位置y轴相差10 则不会移动焦点了。这个判断条件貌似需要修改一下。

**Comment by xianjimli** [comment]
主要支持网格布局的控件。你的界面是什么样子的，贴张图我看看。

**Comment by cuimeng2213** [comment]
![图片](https://user-images.githubusercontent.com/19948474/69046040-0d3e0680-0a33-11ea-9c14-0685160a296c.png)
布局是这样子的，每个都是一个button按钮

**Comment by cuimeng2213** [comment]
![图片](https://user-images.githubusercontent.com/19948474/69046040-0d3e0680-0a33-11ea-9c14-0685160a296c.png)
布局是这样子的，每个都是一个button按钮

**Comment by xianjimli** [comment]
你更新代码试试，rework-focus分支。

**Comment by xianjimli** [comment]
如果不行，你把XML贴上来一下。

**Comment by xianjimli** [comment]
改了，你参考：https://github.com/zlgopen/awtk/blob/master/docs/widget_focus.md
