### ISSUE TITLE
咨询一个关于控件的属性值统一设置的问题？

### ISSUE THREAD

**Issue by lizhenningi** [zlgopen/awtk#295]
您好，咨询一个问题！
       假如我现在已经有一套构建完成的页面布局（即已有构建了多个xml文件），且每个xml文件中都有相同设置的控件B，现在我想统一修改控件B中某一属性的值，您有什么简便的方法吗？

**Comment by lizhenningi** [comment]
比如说在构建各个页面的xml文件时做一些设置等等。。

**Comment by xianjimli** [comment]
是这个问题吗？https://github.com/zlgopen/awtk/issues/293

**Comment by lizhenningi** [comment]
嗯，是这个问题，谢谢
