### ISSUE TITLE
关于如何判定重绘完成？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#297]
使用widget_invalidate或widget_invalidate_force 让某个控件重绘。  如何知道重绘已经完成了？ 程序该如何判定？

**Comment by xianjimli** [comment]
widget_invalidate只是请求重绘，真正重绘在下一个循环，你可以注册控件的EVT_PAINT_DONE，在每次绘制完成时调用。

**Comment by ytchw101** [comment]
哦   另外请教 下：  比如同一界面有2个控件，  请求重绘某1个控件会引起另外一个控件也重绘吗？  如果会  那么会某一时间同时进入EVT_PAINT中吗？ 还是按顺序一个个重绘？？？？

**Comment by xianjimli** [comment]
一个个重绘。
