### ISSUE TITLE
非GUI线程操作控件

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#298]
非GUI线程操作GUI控件可能会产生什么后果？

我创建一个线程在并在线程里执行移动 或者 重绘某个或某些控件   貌似也没啥问题？

**Comment by xianjimli** [comment]
后果不确定。如果你正在非GUI线程移动某个widget，而在移动过程中widget可能被销毁了。

非GUI线程操作GUI控请参考： https://github.com/zlgopen/awtk/blob/master/docs/how_to_non_gui_thread_operate_widget.md

**Comment by ytchw101** [comment]
谢谢
