### ISSUE TITLE
如何设置button常亮？

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#304]
例如我的UI上有5个按钮，默认第1个按钮高亮，
widget_set_state(btn_1,WIDGET_STATE_SELECTED);
//在style xml里面有selected项，如下：
 <style name="btn1_style" >
        <normal icon = "btn_1_n" />
        <pressed icon = "btn_1_p"/>
        <selected icon = "btn_1_s"/>
        <over icon = "btn_1_n"/>
	<disable icon = "btn_1_dis"/>
    </style>
但当我的鼠标移动一下之后，高亮就消失了，变成了normal状态。

**Comment by xianjimli** [comment]
用check button

**Comment by YinWenshuo** [comment]
好，用radio button或check button 都行
