### ISSUE TITLE
window之间的通讯

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#305]
awtk对window之间的通讯有没有既定的方式。例如，我的产品有三个界面：主界面main，子界面A、B。起来默认在主界面main，操作按钮从主界面进入子界面A，在子界面A操作，修改一些公共参数。退出子界面A回到主界面main。
1、从主界面main切到子界面A时，主界面main实际上是在后台运行的吧？
2、主界面main怎么才能实时的得到在子界面A修改的参数，以便实时刷新主界面的某些显示？

**Comment by xianjimli** [comment]
比较优雅的方法是使用观察者模式，借助emitter_t类实现观察者模式非常方便。

**Comment by YinWenshuo** [comment]
emitter_t的使用在文档里面好像说得不多，只是介绍了下emitter的几个接口函数，没有具体的例子。我用了不起作用。我的理解是，先emitter_create，emitter_on，然后再事件分发emitter_dispatch。

awtk-examples里面的例子都没有使用emmiter。

**Comment by YinWenshuo** [comment]
我看最近awtk增加了不少how_to文档，能不能写个如何在awtk里面使用emitter_t来实现观察者模式？

**Comment by xianjimli** [comment]
写一个完整的例子，介绍了4种窗口间通信方式：https://github.com/zlgopen/awtk-inter-win-communication

**Comment by YinWenshuo** [comment]
我目前想到的并且使用的是第一种方式来实现，优点是“老板不敢轻易换人”，哈哈哈。多谢李老师，为了对得起老板，我学习下第三第四种方式。
