### ISSUE TITLE
请教一个关于hscroll_label的问题

### ISSUE THREAD

**Issue by lizhenningi** [zlgopen/awtk#325]
您好！
在文本超长时，我使用hscroll_label，当hscroll_label有焦点时会滚动显示，失去焦点时截断显示。
能否在hscroll_label失去焦点截断显示时，加上提示。
比如：显示文本“11111111111111111”超长，hscroll_label失去焦点时显示“111111...”

**Comment by xianjimli** [comment]
这个功能已经实现了啊。你用最新的代码试试，参考demoui试试。谢谢。

**Comment by lizhenningi** [comment]
好的，谢谢您
