### ISSUE TITLE
我使用rich_text的过程中text_align_h没有生效

### ISSUE THREAD

**Issue by gaoyuan1111** [zlgopen/awtk#326]
我在使用rich_text的过程中，发现text_align_h并没有生效。无论是right还是center。请问是我哪里写错了吗，还是什么其它的原因。 我的目的就是为了实现字符串的居中，并且自动换行后也要居中。下面是我实现的代码。

![图片](https://user-images.githubusercontent.com/57475406/71876940-ebbfe800-3162-11ea-9756-dbbea660a380.png)

![图片](https://user-images.githubusercontent.com/57475406/71876914-d945ae80-3162-11ea-94c0-8c204ef57640.png)
![图片](https://user-images.githubusercontent.com/57475406/71876972-01351200-3163-11ea-90fa-c3d1a7db1e57.png)

**Comment by xianjimli** [comment]
text_align_h还没实现。近期加上吧。

**Comment by gaoyuan1111** [comment]
我刚在使用中发现字体大小也是不生效的。这个也是没有实现的吗？ 还是我使用方法出错了

**Comment by xianjimli** [comment]
字体大小在font属性里指定，看下demoui

**Comment by xianjimli** [comment]
支持了text_align_h，你更新代码试试。

**Comment by scp1011** [comment]
> 支持了text_align_h，你更新代码试试。

text_align_v会支持吗

**Comment by xianjimli** [comment]
> text_align_v会支持吗

我记得是支持的。

**Comment by scp1011** [comment]
> > text_align_v会支持吗
> 
> 我记得是支持的。

好的，但我在designer里是没有实时看到效果，所以就没跑代码看效果
