### ISSUE TITLE
怎么release Linux应用软件？

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#327]
比如说我要提供MusicPlayer-Demo这个软件给到别人，让他在他的ubuntu上运行这个应用软件，单独提供bin文件demo是不行的，我要怎么打包给他？（他不需要源码，仅仅需要看我们的软件在电脑端的运行）

**Comment by YinWenshuo** [comment]
他ubuntu上运行不起来，会报错，缺少libsndio.so.6.1等等

**Comment by xianjimli** [comment]
我也没做过，有几个思路，你可以参考一下：
* 让对方安装一下那几个依赖的包。
* 做成.deb/.rpm之类的包(指定依赖关系)
* 做成web版本，让客户在浏览器里看效果。

**Comment by YinWenshuo** [comment]
多谢，采用了你说的第一种方法，我这里简单点。我让对方安装了那几个依赖包，然后我把bin和assets的界面bin及font等release给到他，可以跑起来。

你说的第二种方法没搞过，暂时不会。

第三种方法，我觉得我有空可以试下，awtk的web版本还没有试过呢。
