### ISSUE TITLE
请教一个问题（多线程：GUI线程和非GUI线程都有）

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#332]
awtk的兄弟们，请教个问题:在main函数里面，在初始化GUI后，我创建了一个非GUI的线程A，A线程用来接收MCU的串口消息，例如某个硬按键被按下时，MCU会发个消息出来。在A线程里面怎么把MCU消息发送到GUI，以便刷新UI。（GUI有好几个window，每次显示只显示一个window，而MCU的消息有可能需要window1处理，也有可能需要window2处理）

main函数：
  application_init();
  /*拉起MCU串口通信*/
  uartComHandelCreate();//非GUI线程A，接收处理MCU消息并发到GUI层

我看了下文档，3.5.5如何自定义事件，

我在非GUI线程A里面这样写：

event_queue_req_t req;
req.event.type = EVT_USER_EVT;
### req.event.target = args;//这个参数传什么呢？？？
main_loop_queue_event(main_loop(), &req);

然后，在GUI里面怎么写呢？awtk在讲这里的时候，例子太简单。有没有你们量产的稍微复杂的例子开源看看？

我的情况是：

我的GUI是在飞思卡尔MX6上跑，MX6通过串口跟一颗MCU通信。

**Comment by xianjimli** [comment]
用idle_queue

**Comment by YinWenshuo** [comment]
> 用idle_queue

这跟main_loop_queue_event差不多啊，我要怎么得到当前窗口的句柄？即idle_queue(on_idle, args);的第二个参数args传什么？应该是传需要响应这个时间的widget吧，那我怎么在非GUI线程得到当前窗口的句柄（上下文ctx）

**Comment by xianjimli** [comment]
main_loop_queue_event是内部使用的，idle_queue是推荐的方式。ctx可以是自定义的数据结构，可以包含窗口的名称和其它信息。在回调函数中查找指定名称的窗口，然后做相应的处理。
