### ISSUE TITLE
scroll_view中克隆控件的显示问题

### ISSUE THREAD

**Issue by hang1014** [zlgopen/awtk#333]
列表中一个button占满一个scroll_view，打开窗口时克隆button，设置焦点在指定的button上，但此时页面上显示的仍是第一个button，按上下键后显示正常，请问有什么方法能刷新它的显示，我试过在xml里手动写几个button再设置焦点显示就是正常的，代码如下

    <list_view style="nobg" auto_hide_scroll_bar="true" h="160" x="0" y="40" w="100%" item_height="160">
      <scroll_view style="nobg" name="connect_list" x="0" y="0" w="100%" h="160" item_width="100%">
		<button name="call_1" style="black" focusable="true" focus="false">
			<label name="call_name" tr_text="" x="125" y="50" w="150"  h="25" style="black"/>	
			<image draw_type="icon" name="logo" x="20" y="35" w="90" h="90" image="incall" />	
			<image draw_type="icon" name="mute_logo" x="20" y="35" w="90" h="90" image="mute_big" visible="false"/>	
			<view name="call_press_num" x="0" y="bottom:-3" w="320" h="35" style="number_input" visible="false" > 
				<label name="input_number" x="10" y="0" w="308" h="35" style="black_left" />
			</view>
		</button>
	  </scroll_view>
      <scroll_bar name="scroll_bar" x="right" y="0" w="5" h="100%" value="0" focusable="false"/>
    </list_view>

			wd = widget_lookup(win, "call_1", TRUE);
			button_count=widget_count_children (wd->parent);
			if(button_count < all_call){
				for(i=0;i<all_call-button_count;i++){
					widget_clone(wd, wd->parent);
				}
			}
		        cur_button = scroll_view->children->elms[cur_show_call];
                    widget_set_focused (cur_button, TRUE);

**Comment by xianjimli** [comment]
可能是widget clone的问题，你更新代码试试。
