### ISSUE TITLE
AWTK可以用什么IDE来加载工程

### ISSUE THREAD

**Issue by yunhai2009** [zlgopen/awtk#334]
您好，AWTK是非常优秀的GUI，不知道如何用类似于qtcreator等IDE来开发，尤其是Linux上？

**Comment by xianjimli** [comment]
界面设计器到这里下载：https://awtk.zlg.cn/index.html

**Comment by yunhai2009** [comment]
您好

> 界面设计器到这里下载：https://awtk.zlg.cn/index.html

除了界面设计器外，像代码类的有IDE吗？

**Comment by xianjimli** [comment]
下一步会开发IDE。

**Comment by yunhai2009** [comment]
> 下一步会开发IDE。
您好
那目前可以用什么替代？另外有必要性来自己开发IDE吗？能后用别人的IDE，这样可以节省人力成本；另外能否把界面设计器去掉试用，否则因为试用期限的限制必然阻碍其发展。

**Comment by xianjimli** [comment]
主要结合AWTK-MVVM开发类似组态软件的IDE。如果你不需要，可以结合AW-Designer + VSCode或AW-Designer+Ecllipse使用即可。

试用期限到了，可以免费续期。

**Comment by yunhai2009** [comment]
> 主要结合AWTK-MVVM开发类似组态软件的IDE。如果你不需要，可以结合AW-Designer + VSCode或AW-Designer+Ecllipse使用即可。
> 
> 试用期限到了，可以免费续期。

非常感谢
