### ISSUE TITLE
vgcanvas如何实现类似安卓的paint.setXfermode()图形混合模式

### ISSUE THREAD

**Issue by webnoise** [zlgopen/awtk#337]
vgcanvas如何实现类似安卓的paint.setXfermode()图形混合模式？

多种效果如下图：
<img width="678" alt="截屏2020-01-30下午11 27 17" src="https://user-images.githubusercontent.com/4745209/73463375-1d218180-43b8-11ea-849b-c3454dcb3a81.png">

**Comment by xianjimli** [comment]
目前不支持。主要是底层不同实现提供的效果很难统一。
