### ISSUE TITLE
如何进行单元测试

### ISSUE THREAD

**Issue by gaoyuan1111** [zlgopen/awtk#338]

**Comment by gaoyuan1111** [comment]
我看了一下awtk的单元测试。想要对我们现有代码做个测试。但是还没有找到跑起来的方法。所以想请教一下 。如何在windows上面执行单元测试。我需要打开什么宏，该如何执行？

**Comment by xianjimli** [comment]
测试AWTK本身，运行bin\runTest。自己的代码可以用gtest编写测试。

**Comment by YinWenshuo** [comment]
[  PASSED  ] 913 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Events.pointer_event_rotate

**Comment by xianjimli** [comment]
> [ PASSED ] 913 tests.
> [ FAILED ] 1 test, listed below:
> [ FAILED ] Events.pointer_event_rotate

你用的之前的版本吧(不过也没有什么影响)。

[==========] 914 tests from 180 test cases ran. (1644 ms total)
[  PASSED  ] 914 tests.
