### ISSUE TITLE
使用master版本在window10 64位编译报错

### ISSUE THREAD

**Issue by zhanglu993** [zlgopen/awtk#340]
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\platforms\pc\semaphore.obj /c src\platforms\pc\semaphore.c -DWIN32 -D_WIN32 -DWINDOWS /EHsc -D_CONSOLE /DEBUG /Od /FS /Z7 -DWITH_64BIT_CPU -DTK_ROOT=\"D:\\SourceCode\\awtk-stm32f103ze\\awtk\" -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_SOCKET -DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DWITH_DESKTOP_STYLE -DSDL2 -DHAS_STD_MALLOC -DWITH_SDL -DWITH_FS_RES -DHAS_STDIO -DHAVE_STDIO_H -DWITH_NANOVG_GPU -DWITH_VGCANVAS_LCD -DWITH_STB_FONT -DWITH_NANOVG_GLES2 -DWITH_NANOVG_GL -D_WIN64 -DSDL_REAL_API -DSDL_HAPTIC_DISABLED -DSDL_SENSOR_DISABLED -DSDL_JOYSTICK_DISABLED -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_HAS_EXCEPTIONS=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_ITERATOR_DEBUG_LEVEL=0 -D_SCL_SECURE=0-D_SECURE_SCL=0 -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE /I. /Isrc /I3rd /Isrc\ext_widgets /I3rd\pixman /I3rd\cairo /I3rd\bgfx\bgfx\include /I3rd\bgfx\bx\include /I3rd\bgfx\bimg\include /I3rd\agge /I3rd\agg\include /I3rd\nanovg /I3rd\nanovg\gl /I3rd\nanovg\base /I3rd\nanovg\agge /I3rd\nanovg\bgfx /I3rd\SDL\src /I3rd\SDL\include /I3rd\agge\src /I3rd\agge\include /I3rd\gpinyin\include /I3rd\libunibreak /I3rd\gtest\googletest /I3rd\gtest\googletest\include /Itools
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27032.1 版
版权所有(C) Microsoft Corporation。保留所有权利。

semaphore.c
src\platforms\pc\semaphore.c(57): error C2039: “name”: 不是“_tk_semaphore_t”的成员
src\platforms\pc\semaphore.c(26): note: 参见“_tk_semaphore_t”的声明
src\platforms\pc\semaphore.c(57): warning C4047: “函数”:“char *”与“int”的间接级别不同
src\platforms\pc\semaphore.c(57): warning C4024: “tk_snprintf”: 形参和实参 1 的类型不同
src\platforms\pc\semaphore.c(57): warning C4047: “函数”:“size_t”与“char [3]”的间接级别不同
src\platforms\pc\semaphore.c(57): warning C4024: “tk_snprintf”: 形参和实参 2 的类型不同
src\platforms\pc\semaphore.c(57): warning C4133: “函数”: 从“tk_semaphore_t *”到“const char *”的类型不兼容
src\platforms\pc\semaphore.c(59): error C2039: “name”: 不是“_tk_semaphore_t”的成员
src\platforms\pc\semaphore.c(26): note: 参见“_tk_semaphore_t”的声明
src\platforms\pc\semaphore.c(59): warning C4090: “函数”: 不同的“const”限定符
src\platforms\pc\semaphore.c(59): warning C4047: “函数”:“const char *”与“int”的间接级别不同
src\platforms\pc\semaphore.c(59): warning C4024: “tk_strncpy”: 形参和实参 2 的类型不同
src\platforms\pc\semaphore.c(59): error C2198: “tk_strncpy”: 用于调用的参数太少
scons: *** [src\platforms\pc\semaphore.obj] Error 2
scons: building terminated because of errors.
(base) PS D:\SourceCode\awtk-stm32f103ze\awtk>

**Comment by xianjimli** [comment]
好的，谢谢。已修改，麻烦更新一下。
