### ISSUE TITLE
希望能加入一个删除控件定时器的功能：widget_remove_timer

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#345]
开启控件定时器后，想中途关闭某个定时器，目前没有函数可以做到
希望可以加入这个功能

类似这样一个函数 
ret_t widget_remove_timer(widget_t* widget, uint32_t timer_id);

[kill_widget_timer.diff.txt](https://github.com/zlgopen/awtk/files/4222812/kill_widget_timer.diff.txt)

**Comment by xianjimli** [comment]
好的，谢谢。
