### ISSUE TITLE
全志F1c200s运行官方Tina linux系统，移植AWTK，闪烁严重，请教怎么解决

### ISSUE THREAD

**Issue by duanchangstar** [zlgopen/awtk#348]
全志F1c200s运行官方Tina_ linux系统，运行自带的minigui和播放mp4视频正常。
编译的是AWTK播放器的Demo，界面闪烁非常严重。请教怎么解决。

视频上传到了B站
https://www.bilibili.com/video/av91122136/

打印信息如下：
root@TinaLinux:/mnt/SDCARD/ha/bin# ./demo
try /mnt/SDCARD/ha/bin
app_root=/mnt/SDCARD/ha
fb_info_t: /dev/fb0
xres=800 yres=480
xres_virtual=800 yres_virtual=960
bits_per_pixel=32 line_length=3200
fb_info_t: red(16 8) green(8 8) blue(0 8)
xpanstep=1 ywrapstep=0
fb_size=1536000 fb_total_size=3072000 fb_nr=2 smem_len=3072000
fb_open clear
fb_open ok
ratio=1.000000 800 480
!!!Asset [name=yellow type=data] not exist!!!
used: 0 bytes 785 blocks
window main open
FBIOPAN_DISPLAY ret=0 yoffset=0
FBIOPAN_DISPLAY ret=0 yoffset=480
FBIOPAN_DISPLAY ret=0 yoffset=0
FBIOPAN_DISPLAY ret=0 yoffset=480
FBIOPAN_DISPLAY ret=0 yoffset=0
FBIOPAN_DISPLAY ret=0 yoffset=480
FBIOPAN_DISPLAY ret=0 yoffset=0
FBIOPAN_DISPLAY ret=0 yoffset=480
FBIOPAN_DISPLAY ret=0 yoffset=0

应该不是系统资源被其他程序占用，运行时已经关闭了Tina自带的minigui和其他程序
暂停demo时，内存占用情况如下
Mem: 25564K used, 33324K free, 32K shrd, 2596K buff, 8208K cached
CPU:   0% usr  10% sys   0% nic  89% idle   0% io   0% irq   0% sirq
Load average: 0.13 0.07 0.03 1/40 171
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
   39     2 root     SW       0   0%   9% [irq/106-sunxi-m]
  171   150 root     R     1168   2%   2% top -d 1
  168   150 root     T    11212  19%   0% ./demo
    1     0 root     S     1164   2%   0% /sbin/init
   94     1 root     S     1164   2%   0% /sbin/klogd -n
  150     1 root     S     1164   2%   0% -/bin/sh
   93     1 root     S     1164   2%   0% /sbin/syslogd -n -m 0
   20     2 root     SW       0   0%   0% [kworker/u2:1]
    9     2 root     SW       0   0%   0% [kworker/0:1]
    6     2 root     SW       0   0%   0% [kworker/u2:0]
   43     2 root     SW       0   0%   0% [mmcqd/0]
    3     2 root     SW       0   0%   0% [ksoftirqd/0]
   18     2 root     SW       0   0%   0% [kswapd0]
    8     2 root     SW       0   0%   0% [kdevtmpfs]
   13     2 root     SW<      0   0%   0% [kblockd]
   11     2 root     SW<      0   0%   0% [bioset]
   10     2 root     SW<      0   0%   0% [writeback]
   12     2 root     SW<      0   0%   0% [crypto]
   17     2 root     SW       0   0%   0% [khungtaskd]
   19     2 root     SW       0   0%   0% [fsnotify_mark]

**Comment by xianjimli** [comment]
貌似驱动没有正确实现FBIOPAN_DISPLAY，你用flush的方式试试。

```c
static lcd_t* lcd_linux_create(fb_info_t* fb) {
    return lcd_linux_create_flushable(fb);
}
```

**Comment by duanchangstar** [comment]
> 貌似驱动没有正确实现FBIOPAN_DISPLAY，你用flush的方式试试。
> 
> ```c
> static lcd_t* lcd_linux_create(fb_info_t* fb) {
>     return lcd_linux_create_flushable(fb);
> }
> ```

已解决，谢谢
