### ISSUE TITLE
遇到几个问题

### ISSUE THREAD

**Issue by 21pages** [zlgopen/awtk#356]
1.子线程里操纵控件,打开关闭窗口有时候也是没问题的,有时候又会死,这是为什么?
2.定时器的回调函数都是在主线程,主循环里的,能不能在调用的线程里
3.子线程里使用timer_add也没问题

**Comment by xianjimli** [comment]
请参考：如何在非GUI线程操作GUI控件： https://github.com/zlgopen/awtk/blob/master/docs/how_to_non_gui_thread_operate_widget.md

**Comment by 21pages** [comment]
> 请参考：如何在非GUI线程操作GUI控件： https://github.com/zlgopen/awtk/blob/master/docs/how_to_non_gui_thread_operate_widget.md
有些代码是同事写的,是在新线程里直接更新界面,更新的是system bar,有一定实时性,但是确实没有出错

**Comment by xianjimli** [comment]
是的。偶尔才会出错

**Comment by 21pages** [comment]
谢谢
