### ISSUE TITLE
为什么输入框是弹出个键盘？

### ISSUE THREAD

**Issue by 243011068** [zlgopen/awtk#358]
win系统不需要弹键盘啊，而且中文也输入不进去

**Comment by xianjimli** [comment]
app type 设置为：APP_DESKTOP

请参考：demos/demo_desktop.c

**Comment by 243011068** [comment]
我看了下是define个值，nodejs中如何定义？
![image](https://user-images.githubusercontent.com/17611077/76397439-05c1b500-63b6-11ea-94ff-475974b69a0e.png)
而且这个init第三个参数是type，第四个才是标题，源文件有误，type我传的TAppType.DESKTOP也无效

**Comment by xianjimli** [comment]
nodejs 版本，编译 PC 版本，请把 src/c/custom.c 中的APP\_SIMULATOR 改成 APP\_DESKTOP，并重新编译。

**Comment by 243011068** [comment]
![image](https://user-images.githubusercontent.com/17611077/76480266-34d53680-6449-11ea-9728-28dca534d082.png)
可以正常输入了，但是有个bug文字输入进去之后，输入上的字还在

**Comment by xianjimli** [comment]
这个是 Windows 和 SDL 的交互，不同平台有些差异，AWTK 没法控制。

**Comment by 243011068** [comment]
没什么办法么，这个太影响体验了

**Comment by xianjimli** [comment]
什么平台？得研究一下 SDL。

**Comment by 243011068** [comment]
win7,64位

**Comment by xianjimli** [comment]
我们测试了几台机器，没有重现。

**Comment by 243011068** [comment]
可能还有什么条件没满足吧，
![image](https://user-images.githubusercontent.com/17611077/76610186-85d15180-6553-11ea-9fcc-25a944e3e71a.png)
zh'ge这个为什么不直接读一下第三个参数？
