### ISSUE TITLE
ring_buffer_peek bug!!!!

### ISSUE THREAD

**Issue by abelbilbil** [zlgopen/awtk#359]
ringbuffer 在溢出的情况下 使用ring_buffer_peek 读取 后会导致 full 被置为FALSE
之后再使用ring_buffer_read 会出现返回错误的情况。
![$A5CVWVGA{0VS$NI`VKVJW](https://user-images.githubusercontent.com/26815306/76411054-f8172a00-63cb-11ea-9215-0b83e027f892.jpg)

**Comment by xianjimli** [comment]
好的，谢谢。
