### ISSUE TITLE
我的屏不带触摸，请问要怎么编译你们的程序呢？

### ISSUE THREAD

**Issue by liusha0002000** [zlgopen/awtk#36]

**Comment by xianjimli** [comment]
什么系统和硬件平台？嵌入式Linux可以用鼠标。

**Comment by liusha0002000** [comment]
嵌入式linux的，不仅没触摸，连鼠标也不能用，就只需要显示就好了，能支持不？

**Comment by xianjimli** [comment]
可以。看看：https://github.com/zlgopen/awtk-linux-fb 去掉tslib就行了。

**Comment by liusha0002000** [comment]
OK，修改SConstruct：
TSLIB_LIB_DIR=''
再设置交叉编译工具，但是构建的时候还是碰到了2个环境变量没找到：CCFLAGS和TK_3RD_ROOT，
在合适的位置添加进去就好了：
os.environ['CCFLAGS'] = CCFLAGS
os.environ['TK_3RD_ROOT'] = TK_3RD_ROOT
之后就可以正常构建了
