### ISSUE TITLE
请教一个死机问题

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#360]
我的程序起来默认窗口为window_main，然后我拉起一个非GUI线程，并在这个非GUI里面调用window_A_open()去打开一个A窗口，然后在A窗口里面点击close按钮调用close_window（win）来关闭A窗口，这样会死机，概率100%。

但如果我在默认窗口直接调用window_A_open()去打开一个A窗口（而不是在非GUI线程里去调用window_A_open（）），然后在A窗口里面点击close按钮调用close_window（win）来关闭A窗口，这样就不会死机

我的问题是：
在非GUI线程里面不能直接像我这样调用window_xxx_open（）来打开一个xxx窗口吗？我的这种在非GUI线程里面打开一个窗口，然后在GUI线程关闭窗口，为什么会死机？如果我必须要在非GUI线程里面开启另一个窗口，我该怎么处理？

多谢！

**Comment by xianjimli** [comment]
请参考：https://github.com/zlgopen/awtk/blob/master/docs/how_to_non_gui_thread_operate_widget.md
