### ISSUE TITLE
滚动视图无法进行拖拽选项上下滚动的操作

### ISSUE THREAD

**Issue by BFDX** [zlgopen/awtk#371]
![image](https://user-images.githubusercontent.com/39155045/76919774-d30f4380-6904-11ea-9367-a2508bf039dd.png)
我模仿空气净化器例子的记录页面，设计出一个滚动视图，视图的结构如上所展示，其中滚动视图的选项可以聚焦，点按，但是无法拖拽进行上下滚动

**Comment by xianjimli** [comment]
直接用list view就可以吧

**Comment by BFDX** [comment]
![image](https://user-images.githubusercontent.com/39155045/76931684-2e9cf980-6924-11ea-95f4-b9e50f3e7a17.png)
jie'gou'gai'chen结构改成listview下面，还是不行

**Comment by xianjimli** [comment]
把xml贴上来

**Comment by BFDX** [comment]
已找到问题，未设置scroll_bar，就不可以拖动。
