### ISSUE TITLE
T9输入法相关，mledit无法通过ADDkey的形式添加单个中文文字，只能做到英文的，可否添加处理？

### ISSUE THREAD

**Issue by BFDX** [zlgopen/awtk#387]
mledit无法通过ADDkey的形式添加单个中文文字，只能通过set_text的形式整个中文字符串设置进去，在覆盖模式下就无法做到单个文字的蓝色底框显示，英文是可以

**Comment by xianjimli** [comment]
T8输入法可以用了：你参考一下这个文档：https://github.com/zlgopen/awtk/tree/t9-exper/src/input_engines
