### ISSUE TITLE
awtk库怎么改动Sconstrut, 以编译为动态库?

### ISSUE THREAD

**Issue by 21pages** [zlgopen/awtk#392]
静态库的话,应用太大, 我们终端远程升级的话会很久

**Comment by xianjimli** [comment]
src/SConscript中，以下代码生成动态库：

113 #ALL_SOURCES=TK_SOURCES + BASE_SOURCES + WIDGETS_SOURCES + EXT_WIDGETS_SOURCES + ['awtk_global.c']
114 #env.SharedLibrary(os.path.join(LIB_DIR, 'awtk_all'), ALL_SOURCES);

**Comment by xianjimli** [comment]
目前支持了同时生成动态库和静态库，具体用法请参考：https://github.com/zlgopen/awtk/blob/master/docs/shared_static.md
