### ISSUE TITLE
没有定义软键盘keyboard.xml的情况下，点击edit控件会崩溃

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#40]
【问题描述】

如果不将awtk下assets\raw\ui\kb_default.xml、assets\raw\styles\keyboard.xml以及键盘用到的图片复制到demo的目录下，点击edit控件会奔溃

假如每次创建demo的时候，如果需要使用键盘都需要从awtk目录下复制keyboard.xm或者kb_***.xml，不知道是否不方便或者还有其他更好的方法我还不知道？或者能否创建edit控件的时候有个默认的键盘?

【初步分析】input_method_default.inc文件下的input_type_open_keyboard()判断逻辑可能存在问题

**Comment by xianjimli** [comment]
已修改。谢谢。如果指定的键盘不存在，就使用缺省的键盘，缺省的键盘不存在就不显示键盘。并打印警告信息。

**Comment by soyzhc** [comment]
9fdb57b9b0ab6e814a26854512ee967fec4cc782
已经解决崩溃问题，

但我们仍然希望awtk可以内置一个键盘，这样用户可以不提供缺省键盘

**Comment by soyzhc** [comment]
好的，我们可以给客户提供的一个做好的模板工程，里面定义有默认的键盘xml，降低使用难度
