### ISSUE TITLE
AWTK Designer打开提示错误，初始化失败

### ISSUE THREAD

**Issue by huangxunyan** [zlgopen/awtk#401]
打开AWTK Designer时出现弹窗，提示初始化失败，重装过软件了，还是一样。

**Comment by a32425262** [comment]
参考这个https://blog.csdn.net/coderALEX/article/details/112623096
修复wmi，修复软件地址：
https://www.majorgeeks.com/files/details/tweaking_com_repair_wmi.html

**Comment by a32425262** [comment]
参考这个https://blog.csdn.net/coderALEX/article/details/112623096
修复wmi，修复软件地址：
https://www.majorgeeks.com/files/details/tweaking_com_repair_wmi.html
