### ISSUE TITLE
死机反汇编dump

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#403]
dump.tar.gz压缩包里面的aps是我基于awtk做的应用软件，libeventhubproxy_backtrace.txt是死机时保存的backtrance，aps.map是aps bin文件反汇编的dump文件，看样子好像是我在aps应用软件里面调用widget_set_tr_text，在widget_set_tr_text里面有调用widget_set_prop,然后死掉了。但具体为什么死了，我对汇编不懂，没追明白，不知道awtk的兄弟们能不能帮我看看。谢谢！
[dump.tar.gz](https://github.com/zlgopen/awtk/files/4615249/dump.tar.gz)

**Comment by xianjimli** [comment]
看不出什么问题。如果你在linux上运行，建议在linux-fb下用valgrind排除一下内存问题。
