### ISSUE TITLE
edit控件按下删除键(x)时，不会触发EVT_VALUE_CHANGING事件

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#41]
【问题描述】edit控件按下删除键(x)的时候，不会触发EVT_VALUE_CHANGING事件，按下其他键例如a-z则会触发

【初步分析】我这边试了一下在edit.c文件中的edit_delete_prev_char和edit_delete_next_char函数下添加:edit_dispatch_event(widget, EVT_VALUE_CHANGING);就可以了，不知道这样是否可行

**Comment by xianjimli** [comment]
已修改。谢谢。

**Comment by soyzhc** [comment]
9fdb57b9b0ab6e814a26854512ee967fec4cc782
