### ISSUE TITLE
编译源码提示错误，请教？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#411]
之前编译源码都好的， 最近编译最新awtk源码或者老源码 都提示
：cl: 命令行 error D8021 :无效的数值参数“/FS”
scons: *** [3rd\glad\glad.obj] Error 2
scons: building terminated because of errors.

重装python 和 scons  也是一样？  啥问题。。？

**Comment by xianjimli** [comment]
我这里没问题。换台机器试试，去掉这个参数应该也可以。
