### ISSUE TITLE
图片翻译问题

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#417]
使用图片翻译后，进入有图片翻译的界面，一直打印
（中文时）
!!!Asset [name=Error_Continue_n_zh_CN type=image] not exist!!!
!!!Asset [name=Error_Cancel_n_zh_CN type=image] not exist!!!
（英文时）
!!!Asset [name=Error_Continue_n_en_US type=image] not exist!!!
!!!Asset [name=Error_Cancel_n_en_US type=image] not exist!!!

实际上在我的工程图片文件夹下面有Error_Continue_n_zh、Error_Cancel_n_zh，Error_Cancel_n_en，Error_Continue_n_en四张图片，切换语言时，对应语言的图片也显示出来了。

看了下文档：
在英文环境下， 加载图片时会按下列顺序查找（中文环境下也类似） ：
 flag_en_US
 flag_en
 flag_

我的图片情况是第二种情况flag_en/flag_zh，我认为在找到flag_en/flag_zh图片时，不应该去疯狂的打印!!!Asset [name=Error_Continue_n_en_US type=image] not exist!!!
!!!Asset [name=Error_Cancel_n_en_US type=image] not exist!!!

**Comment by xianjimli** [comment]
好的。我关闭了这条log
