### ISSUE TITLE
请教Edit控件接收回车按键按下事件方法

### ISSUE THREAD

**Issue by huangxunyan** [zlgopen/awtk#420]
问题描述：我想做一个Edit，编辑时使用软键盘，软键盘上有一个确认键(key:return)，想在按下后触发Edit的事件进行一些处理，但是我在按下后并没有触发EVT_KEY_PRESS事件，请问下应该怎么做？
PS:在网上搜到QT的做法是有一个事件过滤器eventFilter，但在AWTK上没找到，请问有什么方法能实现我想要的功能。

**Comment by xianjimli** [comment]
稍等，我写个文档。

**Comment by xianjimli** [comment]
你参考这个文档：https://github.com/zlgopen/awtk/blob/master/docs/how_to_use_action_text.md

**Comment by huangxunyan** [comment]
@xianjimli

**Comment by huangxunyan** [comment]
@xianjimli 
好的，谢谢，按照文档的方法可以接收到事件了。之前因为没有通过edit_set_action_text把默认的action_text:done改了，所以一直没触发EVT_IM_ACTION事件。
