### ISSUE TITLE
键盘按s卡死？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#422]
您好，我的问题就是中文输入时，一直按键盘的's',会出现卡死！  去年年底反映过这个问题，然后后来你们解决了，我于今年1月份时更新AWTK源码后没有卡死了。   我现在又更新到AWTK 1.4.1版本后 又有这个情况了，

**Comment by xianjimli** [comment]
改了，谢谢。你更新一下。

**Comment by ytchw101** [comment]
好 谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 中午11:15
收件人: "zlgopen/awtk"<awtk@noreply.github.com&gt;; 
抄送: "金涵电子业务"<2519007921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk] 键盘按s卡死？ (#422)





 
改了，谢谢。你更新一下。
