### ISSUE TITLE
contextmenu 哪个控件怎么用？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#424]
示例中有个contextmenu 是哪个控件？有没例程呢？

**Comment by xianjimli** [comment]
没有控件，其实就是popup窗口。你可以参考这个文件：demos/assets/default/raw/ui/menu_point.xml

唯一特殊的就是self_layout，可以在点击的位置弹出：

```
self_layout="menu(w=128,h=90)"
```
