### ISSUE TITLE
使用slide_view画面刷新慢

### ISSUE THREAD

**Issue by huangxunyan** [zlgopen/awtk#427]
描述：在slide_view里面加入一个button，改变button的背景颜色，需要鼠标移动到button上或者滑动slide_view时，button的背景颜色才改变。

改变button颜色用的API是style_set(child_widget->astyle, WIDGET_STATE_NORMAL, STYLE_ID_BG_COLOR, &v1);

![微信截图_20200615165706](https://user-images.githubusercontent.com/31651559/84638317-674f6d80-af29-11ea-91da-a7ee1ad3252e.png)
![微信截图_20200615165719](https://user-images.githubusercontent.com/31651559/84638322-6a4a5e00-af29-11ea-9d62-76293ce05015.png)

**Comment by xianjimli** [comment]
1.去掉按钮的圆角试试。
2.看看有没有使用半透的颜色。

**Comment by huangxunyan** [comment]
使用了其他另外一个接口widget_set_style_str不会出现这个问题。
