### ISSUE TITLE
是否有计划提供C#绑定？

### ISSUE THREAD

**Issue by zxslzx** [zlgopen/awtk#435]

**Comment by xianjimli** [comment]
C#不是有很强大的GUI，支持它好像没有什么意义。

**Comment by zxslzx** [comment]
> C#不是有很强大的GUI吗，支持它好像没有什么意义。

可以用在linux嵌入式上,  net core + awtk

**Comment by xianjimli** [comment]
好的，有时间我研究一下。

**Comment by zxslzx** [comment]
> 好的，有时间我研究一下。

我参照 java 绑定实现了C#绑定。 并成功运行了C#版 demo_tr_app，但是切换不了中文，会是什么原因?  看日志也什么错误信息

**Comment by xianjimli** [comment]
* 先看看资源assets/default/raw/strings/*.bin是否存在。
* 能调试的话，用调试器跟到C代码里看看。

**Comment by zxslzx** [comment]
> * 先看看资源assets/default/raw/strings/*.bin是否存在。
> * 能调试的话，用调试器跟到C代码里看看。

感谢指导, 已经解决, 是字符大小写问题
