### ISSUE TITLE
linux-arm显示gif图片后，cpu占用率比较高，隐藏gif图片后，cpu不恢复，仍然高

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#437]
我的测试xml代码如下：

<window style="default">
    <gif name="test_gif" x="192" y="197" w="650" h="307" image="laugh" visible="FALSE"/>
    <view x="0" y="632" w="100%" h="88" style="bottomBtnBar_s" children_layout="default(r=1,c=3)"> 
       <button name="btn_set" x="1098" y="634" w="182" h="86" style="btn_set_s"/>
       <radio_button name="btn_front" x="326" y="634" w="154" h="86" style="btn_front_s" value="TRUE"/>
       <radio_button name="btn_rear" x="480" y="634" w="154" h="86" style="btn_rear_s"/> 
    </view>
</window>

开机默认gif不显示，此时查看cpu占用率不高（我的平台是1%），我点击某个按钮后，让gif图片visible，此时cpu占用率升高（我的平台是13%左右），刷gif图片时cpu占用率高点可以接受，但是，当我点击某个按钮让这个gif图片隐藏不显示，这个时候，cpu占用率还是13%左右。为啥gif图片隐藏了cpu占用率不会降下来？？

我的逻辑代码如下：

static ret_t on_open_dialog_set(void* ctx,event_t* e)
{
    (void)e;
    return dialog_user_set_open();
}

static ret_t on_rear_btn(void* ctx,event_t* e)
{
    log_debug("##%s,enter,\n",__func__);
    (void)e;
    widget_t* win = WIDGET(ctx);
    widget_t* giftest = widget_lookup(win,"test_gif",FALSE);
    widget_set_visible(giftest,FALSE,FALSE);

    return RET_OK;
}

static ret_t on_front_btn(void* ctx,event_t* e)
{
    log_debug("##%s,enter,\n",__func__);
    (void)e;
    widget_t* win = WIDGET(ctx);
    widget_t* giftest = widget_lookup(win,"test_gif",FALSE);
    widget_set_visible(giftest,TRUE,FALSE);

    return RET_OK;
}

static ret_t init_widget(void* ctx, const void* iter)
{
    widget_t* widget = WIDGET(iter);
    (void)ctx;
    if (widget->name != NULL)
    {
        const char* name = widget->name;
        widget_t* win = widget_get_window(widget);
        if(tk_str_eq(name, "btn_set"))
        {
            if (win)
            {
               widget_on(widget, EVT_CLICK, on_open_dialog_set,win);
            }
        }
        else if(tk_str_eq(name, "btn_rear"))
        {
            if (win)
            {
               widget_on(widget, EVT_CLICK, on_rear_btn,win);
            }
        }
        else if(tk_str_eq(name, "btn_front"))
        {
            if (win)
            {
               widget_on(widget, EVT_CLICK, on_front_btn,win);
            }
        }
    }

    return RET_OK;
}

**Comment by YinWenshuo** [comment]
不同的gif图片，cpu占用率表现也不同。
我是关闭了脏矩形：lcd->support_dirty_rect = FALSE;

**Comment by xianjimli** [comment]
改了，你更新代码试试。谢谢

**Comment by YinWenshuo** [comment]
可以了 ，谢谢。
