### ISSUE TITLE
请教一下，tslib添加进去，提示没定义的，有人遇到过吗，是什么原因

### ISSUE THREAD

**Issue by qwegary** [zlgopen/awtk#440]
![image](https://user-images.githubusercontent.com/55617263/86454430-cd255d00-bd51-11ea-9aca-f24beb453b38.png)
编译不通过，一直提示函数没定义

**Comment by xianjimli** [comment]
通常是没找到对应的库，或者库的格式不匹配。

**Comment by qwegary** [comment]
我把库文件tslib.a拿掉直接提示cannot find -lts，把库加上去，就是提示里面的一些函数没定义，但是查看tslib.h文件中，存在对应的函数，tslib.a  tslib.h是板卡上其他demo上使用的。

**Comment by qwegary** [comment]
![image](https://user-images.githubusercontent.com/55617263/86547012-fddfdf00-bf69-11ea-899b-f723e93aad0a.png)

**Comment by xianjimli** [comment]
看看文件格式：

```
file tslib.a
```

**Comment by qwegary** [comment]
![image](https://user-images.githubusercontent.com/55617263/86554521-705bb980-bf80-11ea-8842-a36603857564.png)

**Comment by qwegary** [comment]
![image](https://user-images.githubusercontent.com/55617263/86568160-09013200-bf9f-11ea-8028-21c0c7d8d722.png)

**Comment by xianjimli** [comment]
那不知道了。百度一下。

**Comment by YinWenshuo** [comment]
你用的是.a静态库?我用的是.so动态库，没问题啊。估计你的库打包有问题，找不到对应的函数。@qwegary

**Comment by qwegary** [comment]
我试一下用动态库的

**Comment by qwegary** [comment]
使用动态链接库可以正常跑起来了，感谢
