### ISSUE TITLE
自己画了个UI，移植到嵌入式设备之后，一直打印找不到图片

### ISSUE THREAD

**Issue by qwegary** [zlgopen/awtk#443]
![image](https://user-images.githubusercontent.com/55617263/87026485-6353fa00-c20e-11ea-8ec4-aa3c526488e0.png)
图片名称为空，乍回事呢

**Comment by xianjimli** [comment]
看看xml，图片名是否为""

**Comment by qwegary** [comment]
找到了，一个拖动条里面有一个背景图片为空的属性，删掉属性就可以了。但是在工具里面显示是 无 的。这个不知道什么原因了。
