### ISSUE TITLE
请教字体解析。

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#444]
我程序需要实现解析文字得到字模数据。目前使用方法如下：
	  glyph_t gy;
	  font_size_t size = GetFontSize(font_name);
	  font_t*  ft = font_manager_get_font(font_manager(), font_name, size);
           font_get_glyph(ft, pwstr[i], font_size, &gy);
采用这种方式得到某个字的字模数据 即gy.data ， 但是通过字模数据转成图片显示这个字 锯齿较严重。

看源码里FT_LOAD_TARGET_MONO 渲染 不知道 能不能解决 ？ 不知道怎么用/?
或者说 这个 font_ft_mono_create 咋用的？ 谢谢

注： LCD屏非单色LCD

**Comment by xianjimli** [comment]
要用freetype才行，stb不支持。

**Comment by ytchw101** [comment]
有啥好方法  解决解析文字后 的锯齿问题呢？  通过widget_set_text 显示的字体 看着显示还行  不知道在哪里做的平滑（抗锯齿）处理呢？

**Comment by xianjimli** [comment]
你是不要抗锯齿功能吗？都是启用抗锯齿功能的，MONO是去掉抗锯齿功能。

**Comment by ytchw101** [comment]
AWTK源码中对字体 抗锯齿 处理在哪个文件里呢？

**Comment by xianjimli** [comment]
这个是stb/freetype自己处理的。
