### ISSUE TITLE
关于改变多选按钮的数值问题

### ISSUE THREAD

**Issue by qwegary** [zlgopen/awtk#448]
![image](https://user-images.githubusercontent.com/55617263/87738978-39ec2d00-c811-11ea-9373-cb8a7535fcd3.png)
我的目的是想做一个单选，点击其中一个，其他的几个都去掉勾选状态。
![image](https://user-images.githubusercontent.com/55617263/87739078-8e8fa800-c811-11ea-98c9-76cae30e16be.png)
我这边绑定两个按钮到，图片上的两个函数中，一个能正常使用，另外一个直接闪退，是什么原因。
或者有没有办法在事件触发函数上，获取到触发这个函数的控件是哪一个？

**Comment by xianjimli** [comment]
为什么不用radio_button

**Comment by xianjimli** [comment]
获取当前触发事件的按钮：
```c
widget_t* target = WIDGET(e->target);
```

**Comment by qwegary** [comment]
好的，感谢
