### ISSUE TITLE
软键盘需要增加一个切换“中文/英文“的按钮

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#45]
在输入文本的edit控件弹出的键盘，目前默认都是输入中文输入法的
如果要输入英文，必须先把英文输入到候选字栏，再按确认键把英文送到edit控件
用起来不是很方便

希望和android那样，添加一个“中文/英文”切换按钮，可以切换输入法模式，或直接输入英文模式

**Comment by xianjimli** [comment]
已修改。谢谢。没找到合适的图标，可能需要美术设计一个。

**Comment by soyzhc** [comment]
9452323c7f52216b759378d9c764ca6bd469c359

但建议图标显示当前输入状态，而不是切换后的状态
