### ISSUE TITLE
使用image_animation控件的问题

### ISSUE THREAD

**Issue by hanlong-coclean** [zlgopen/awtk#450]
使用image_animation动画来切bmp图片，初始化动画控件的时候设置了auto_play的属性为FALSE，板子刚上电后大概几秒后死机了，CmBacktrace查看log发现是bitmap_cache_destroy调用tk_free的时候挂掉的，这是什么原因呢
![image](https://user-images.githubusercontent.com/56382720/88160246-f9d9df80-cc40-11ea-9f05-7aa05fe4a439.png)

**Comment by xianjimli** [comment]
我在PC上没有重现，你用最新代码试试。

**Comment by hanlong-coclean** [comment]
我这里也不是每次都会死掉的，上面的问题也是第一次出现的，没有复现的问题隐藏很深，我们改从哪个方向去排查呢

**Comment by hanlong-coclean** [comment]
我这里也不是复现，上面那个问题也是第一次遇到，正好抓到log了，上面那些log能大致看出来是哪里的问题么
