### ISSUE TITLE
请教一下，如何在代码种动态改变控件的背景图？

### ISSUE THREAD

**Issue by qwegary** [zlgopen/awtk#451]
就是想实现，一个按钮，本来背景图是图1，点击之后变成图2，再点击变成图3。
在API文档里面没看到有相关的修改。widget_t里面也没找到能修改背景图的接口。
有什么好办法可以实现呢

**Comment by xianjimli** [comment]
image_value控件有这样一个功能，不知是不是你需要的，你可以参考demoui:

```xml
<image_value  value="0" image="battery_" click_add_delta="1" min="0" max="5"/>
```

**Comment by qwegary** [comment]
好的，感谢
