### ISSUE TITLE
awtk designer续期问题

### ISSUE THREAD

**Issue by innovak** [zlgopen/awtk#454]
awtk designer已经到期,个人用户该如何续期?如需购买的话该如何联系?

**Comment by tangMans** [comment]
请看AWTK Designer 0.1.6安装目录下：Docs\AWTK Designer快速安装指南.pdf 中的 “1.5.1 许可管理”章节

**Comment by innovak** [comment]
感谢回复,但是安装指南中只提到了提供公司信息后可能获得赠送券,作为个人用户似乎无法获得?另外是否有购买卡券的方式?因为即使赠送卡券也只能使用一个季度.

**Comment by tangMans** [comment]
1、没有公司信息，可以填写学校信息等

2、卡券目前不支持购买方式

3、个人用户也有可能获取卡券，但需尽量提供个人真实信息，这样方便通过审核
