### ISSUE TITLE
软键盘隐藏后，还是会保留上一次输入的字符（还没有确认输入的字符）

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#46]
在文本edit控件弹出的键盘，输入一些英文在候选框，但先不确认选哪个候选字
直接隐藏键盘，再次点击edit弹出键盘，
再输入一些英文，发现隐藏键盘前输入的内容还保留着

建议隐藏键盘后，上次输入的内容清空

**Comment by xianjimli** [comment]
已修改。谢谢。

**Comment by soyzhc** [comment]
9452323c7f52216b759378d9c764ca6bd469c359
