### ISSUE TITLE
关于打包后编译失败问题

### ISSUE THREAD

**Issue by HonSinsin** [zlgopen/awtk#462]
系统环境：VM 14 PRO 虚拟机上的 WIN10 64 位系统
AWTK 版本：0.1.6
问题：点击项目 --> 打包 --> 编译，命令行内提示 `'scons' 不是内部或外部命令，也不是可运行程序或批处理文件。`

根据编译提示操作：
工程目录下有 `SConstruct` 文件 且  `awtk_root=‘C:/AWTK/SDK/awtk’` 的路径存在。
新建工程也是这样的

还有个情况是：登陆的账户状态为（离线）提示许可认证异常

**Comment by xianjimli** [comment]
应该是编译环境没安装好，请参考一下：https://github.com/zlgopen/awtk/blob/master/README_zh.md
