### ISSUE TITLE
怎么固定显示输入法键盘呢？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#463]
1.edit控件获得焦点后输入法键盘弹出， edit失去焦点就会自动关闭输入法。 怎么样固定这个键盘始终打开？

2.使用 method edit_set_open_im_when_focused 设置编辑器是否在获得焦点时打开输入法。 设置为false为什么 点击edit后输入法键盘还能弹出？

**Comment by xianjimli** [comment]
edit_set_open_im_when_focused 属性有两个用途：
* 设置默认焦点时，打开窗口时不弹出软键盘。
* 用键盘切换焦点时，编辑器获得焦点时不弹出软键盘。

**Comment by xianjimli** [comment]
> 焦点



> 1.edit控件获得焦点后输入法键盘弹出， edit失去焦点就会自动关闭输入法。 怎么样固定这个键盘始终打开？
目前不行，什么样的场景需要？具有普适性的话，我加个属性来控制。

**Comment by ytchw101** [comment]
也不是什么特殊场景&nbsp; 主要比如我LCD某个区域 就是用来显示键盘&nbsp; 但点击非edit控件后失去焦点后键盘自动关闭了&nbsp; 这样感觉 那一块就空了 （界面看起来不对称 ）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 上午7:45
收件人: "zlgopen/awtk"<awtk@noreply.github.com&gt;; 
抄送: "金涵电子业务"<2519007921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk] 怎么固定显示输入法键盘呢？ (#463)





  
焦点
   
1.edit控件获得焦点后输入法键盘弹出， edit失去焦点就会自动关闭输入法。 怎么样固定这个键盘始终打开？
 目前不行，什么样的场景需要？具有普适性的话，我加个属性来控制。

**Comment by ytchw101** [comment]
个人觉得 输入法键盘 应该 加个属性来控制 键盘是否固定 并最好在键盘获得焦点时自动适配界面的某个编辑框控件，目前我们基于AWTK的嵌入式产品 还没出去多少 就已经有几个客户提出键盘能否固定  因为在LCD触摸屏上 很容易碰到除编辑框外的其他地方 导致编辑框失去焦点从而导致键盘关闭问题 - 这样以来不进界面空了一块  客户还得再次点下编辑框 键盘才能出来。

**Comment by xianjimli** [comment]
好的。谢谢

**Comment by xianjimli** [comment]
```c
  /**
   * @property {bool_t} close_im_when_blured
   * @annotation ["set_prop","get_prop","readable","persitent","design","scriptable"]
   * 
   * 是否在失去焦点时关闭输入法(默认是)。
   *
   */
  bool_t close_im_when_blured;
```

**Comment by ytchw101** [comment]
mledit&nbsp; 为啥不加&nbsp;close_im_when_blured ？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年9月30日(星期三) 上午9:27
收件人: "zlgopen/awtk"<awtk@noreply.github.com&gt;; 
抄送: "金涵电子业务"<2519007921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk] 怎么固定显示输入法键盘呢？ (#463)





   /**    * @property {bool_t} close_im_when_blured    * @annotation ["set_prop","get_prop","readable","persitent","design","scriptable"]    *     * 是否在失去焦点时关闭输入法(默认是)。    *    */   bool_t close_im_when_blured;
