### ISSUE TITLE
open 一个Dialog后，在代码中修改自身的布局参数不会立即生效

### ISSUE THREAD

**Issue by likesubject** [zlgopen/awtk#467]
![image](https://user-images.githubusercontent.com/15309266/91287936-f3e89880-e7c2-11ea-858f-5093a6d8df9a.png)
**在代码中修改自身布局后弹出的Dialog和xml中定义的大小一致**
![image](https://user-images.githubusercontent.com/15309266/91288234-5772c600-e7c3-11ea-9152-fcd80d1df147.png)
**当移动窗口后才会变成设置的大小**
![image](https://user-images.githubusercontent.com/15309266/91288359-7cffcf80-e7c3-11ea-9748-bd605c92fc76.png)
**并且设置强制无效也没有作用。**
想问一下，如在代码中修改dialog后，如何才能立即生效？

**Comment by xianjimli** [comment]
调用layout函数
