### ISSUE TITLE
疯狂打印：stb_load_image：67 stb_data != NULL

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk#470]
疯狂打印如下：
stb_load_image：67 stb_data != NULL
stb_load_image：67 stb_data != NULL
stb_load_image：67 stb_data != NULL
stb_load_image：67 stb_data != NULL

（ARM+LINUX平台）
观察界面发现有张图片没显示出来，关机重启后，正常了，开始没显示出来的那张图片也显示出来了。

我想请问下，什么情况下可能会导致某张或者某几张图片加载不成功？
图片比较大会可能导致这个问题吗？（上面问题没显示出来的图片大小70kb，长宽：1280*88）

**Comment by YinWenshuo** [comment]
stbi_load_from_memory这个函数的实现在第三方库里面是吧

**Comment by xianjimli** [comment]
应该是内存不够。

**Comment by xianjimli** [comment]
如果是png，可能需要450K内存。

**Comment by YinWenshuo** [comment]
> 如果是png，可能需要450K内存。

什么意思？意思是我这70k的png图片在load的过程中实际上需要450k内存？
