### ISSUE TITLE
多点触控问题

### ISSUE THREAD

**Issue by woshiyooyoo** [zlgopen/awtk#472]
请问AWTK控件是否支持多点触控？比如图片控件通过两个手指触控放大或缩小图片显示。

**Comment by xianjimli** [comment]
目前还不支持，需要自己做。你打算在什么平台上使用

**Comment by woshiyooyoo** [comment]
主要是android平台

**Comment by xianjimli** [comment]
基于SDL平台的系统，如android、ios、windows、macos和linux(desktop)，都支持了旋转和缩放多点手势事件，你用最新代码试试。但是图片的缩放要自己根据手势实现

参考：

* https://github.com/zlgopen/awtk-hello/blob/master/src/window2.c

* https://github.com/zlgopen/awtk/blob/master/src/base/events.h

**Comment by woshiyooyoo** [comment]
AWTK越来棒了！支持旋转和多点触摸！！！

**Comment by xianjimli** [comment]
谢谢支持
