### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ihanhua** [zlgopen/awtk#48]
linux 编译没问题，启动出现段错误。
![image](https://user-images.githubusercontent.com/40795109/49119684-375b5d80-f2e4-11e8-80fe-b102c0abe4ef.png)

**Comment by xianjimli** [comment]
什么系统？不支持Ubuntu 16之前的老系统(好像是老系统不支持OpenGL 3)。

**Comment by ihanhua** [comment]
![image](https://user-images.githubusercontent.com/40795109/49360181-607c5380-f713-11e8-985c-b7157a36e1d9.png)
