### ISSUE TITLE
tools/image_dither/main.c:104:17: error: implicit declaration of function 'image_gen' is invalid in C99

### ISSUE THREAD

**Issue by suzp1984** [zlgopen/awtk#480]
在Mac下编译失败，原因是image_dither.h头文件有点笔误。

[image_dither_h.txt](https://github.com/zlgopen/awtk/files/5275042/image_dither_h.txt)

--- a/tools/image_dither/image_dither.h
+++ b/tools/image_dither/image_dither.h
@@ -19,8 +19,8 @@
  *
  */

-#ifndef IMAGE_GEN_H
-#define IMAGE_GEN_H
+#ifndef IMAGE_DITHER_H
+#define IMAGE_DITHER_H

 #include "widgets/image.h"

@@ -33,4 +33,4 @@ ret_t image_dither_image_wirte_png_file(const char* output_file, bitmap_t* image

 END_C_DECLS

-#endif /*IMAGE_GEN_H*/
+#endif /*IMAGE_DITHER_H*/

**Comment by xianjimli** [comment]
好的，谢谢你。
