### ISSUE TITLE
输入法键盘如何设置向左、向右或从上往下弹出呢？

### ISSUE THREAD

**Issue by ytchw101** [zlgopen/awtk#483]
如题.

**Comment by ytchw101** [comment]
另外请问上次提的键盘能否固定显示的问题    有打算实现吗？！

**Comment by xianjimli** [comment]
> 另外请问上次提的键盘能否固定显示的问题 有打算实现吗？！

已经实现了啊，告诉过你啊。

**Comment by xianjimli** [comment]
支持这个比较麻烦，要向不同方向推动窗口，也没有什么必要。

**Comment by ytchw101** [comment]
哦 好&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 晚上6:13
收件人: "zlgopen/awtk"<awtk@noreply.github.com&gt;; 
抄送: "金涵电子业务"<2519007921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk] 输入法键盘如何设置向左、向右或从上往下弹出呢？ (#483)





  
另外请问上次提的键盘能否固定显示的问题 有打算实现吗？！
  
已经实现了啊，告诉过你啊。
