### ISSUE TITLE
如何实现 VNC server

### ISSUE THREAD

**Issue by zxslzx** [zlgopen/awtk#484]
想实现VNC server,  有没有接口可以读取framebuffer 数据？

**Comment by xianjimli** [comment]
可以用 widget_take_snapshot

**Comment by zxslzx** [comment]
嗯，  另外不知是否可以获取 framebuffer dirty 的区域，比如 某个控件重绘了, 通过回调获取framebuffer更新的矩形区域，只把这内容发往 vnc client, 以减少数据量

**Comment by xianjimli** [comment]
可以从native window中获取。
