### ISSUE TITLE
最新版本的AWTK,控件mledit出现右边滑动条以及上下按键不能正常控制文本显示区域移动的问题

### ISSUE THREAD

**Issue by hantianheng** [zlgopen/awtk#487]
你好：
       我在使用最新版本的AWTK时，发现扩展控件mledit出现右边滑动条以及上下按键不能正常控制文本显示区域移动的问题，该问题在awtk的demoui演示中可以看得到。

**Comment by xianjimli** [comment]
改了。你更新代码试试。谢谢
