### ISSUE TITLE
windows 下无法编译demo，报错无法找到powershell.exe文件。

### ISSUE THREAD

**Issue by puding520** [zlgopen/awtk#490]
windows 下无法编译demo，报错无法找到powershell.exe文件。
  我尝试的解决方法     1 ： 后来我又重装了powershell还是不行。2：添加了环境变量。反正就是一直编译通不过，一直报错无法找到powershell.exe文件。
![1602744956(1)](https://user-images.githubusercontent.com/63795829/96087673-cf718880-0ef6-11eb-81c0-fcddf0de0462.png)

**Comment by soyzhc** [comment]
可以尝试把 C:\Windows\System32\WindowsPowerShell\v1.0 下的 powershell.exe 拷贝到 windows 目录下

**Comment by puding520** [comment]
> 可以尝试把C：\ Windows \ System32 \ WindowsPowerShell \ v1.0下一个的powershell.exe复制到Windows目录下

**Comment by puding520** [comment]
> 可以尝试把C：\ Windows \ System32 \ WindowsPowerShell \ v1.0下一个的powershell.exe复制到Windows目录下

非常感谢，已经可以正常编译了
