### ISSUE TITLE
AssetLoaderZip test cases basic & reader FAILED

### ISSUE THREAD

**Issue by suzp1984** [zlgopen/awtk#492]
首先，assets/default/raw/ui/basic.bin 路径名变更为 res/assets/default/raw/ui/basic.bin;
再次，数据也有问题；

使用，python scripts/update_res.py all 似乎更新了好多数据，是不是也要把更新了的数据提交下。

**Comment by suzp1984** [comment]
已经解决

**Comment by xianjimli** [comment]
谢谢
