### ISSUE TITLE
edit框输入长文本删除时的问题

### ISSUE THREAD

**Issue by hang1014** [zlgopen/awtk#496]
edit框输入很长的文本（超过控件宽度的2倍），使用BACKSPACE键删除，会出现edit框显示为空，实际上前边还有内容的问题。这个时候按左键可以让文本右移，但在没有左右键的情况下就没有办法看到前边的内容了。请问能不能在文本超长的情况下删除的时候让文本自动右移呢？

**Comment by xianjimli** [comment]
改了，你更新试试。谢谢
