### ISSUE TITLE
很强大

### ISSUE THREAD

**Issue by uxctx** [zlgopen/awtk#509]
很强大

只不过个人有个小建议，建议尝试用c++写，不用c++那些高级特性，stl也不用，就用  c + class ，c++的面向对象很适合抽象业务，比如写界面，这样更方便，代码量估计会更小，而且设计上可能更清洁。

**Comment by xianjimli** [comment]
你可以用C++绑定：https://github.com/zlgopen/awtk-cpp

**Comment by uxctx** [comment]
额，我的意思是用c++的面向对象去实现awtk核心，这样构建可能会更清晰，不用stl，不用任何高级特性，
