### ISSUE TITLE
无法选择多于3个的radio_button

### ISSUE THREAD

**Issue by YasirLiang** [zlgopen/awtk#51]
问题的描述是这样的：在scroll_view增加一组radio_button（多于3个）后，第1个、第2个、第3个radio_button可以选中，第4个或之后的radio_button就无法选中了。是不是新提交代码后无法支持多于3个radio_button的组还是其他原因，因为前面的提交是可以的。

**Comment by xianjimli** [comment]
已修改。谢谢。
