### ISSUE TITLE
gen_floder -> gen_folder 拼写错误

### ISSUE THREAD

**Issue by suzp1984** [zlgopen/awtk#513]
locations: 
tools/ui_gen/xml_to_ui/xml_to_ui.c
tools/image_gen/main.c
tools/res_gen/main.c
tools/str_gen/main.cc
tools/svg_gen/bsvg_gen.cc
tools/theme_gen/main.cc

gen_floder -> gen_folder 拼写错误

似乎很多都拼成了floder，不知道是否是拼写错误。

[folder_spell.diff.txt](https://github.com/zlgopen/awtk/files/5818720/folder_spell.diff.txt)

**Comment by xianjimli** [comment]
合并了。感谢。
