### ISSUE TITLE
VS2017环境下，编译失败

### ISSUE THREAD

**Issue by nanfang2000** [zlgopen/awtk#53]
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25831 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

glad.c
3rd\glad\glad.c(21): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
scons: *** [3rd\glad\glad.obj] Error 2
scons: building terminated because of errors.

**Comment by nanfang2000** [comment]
python2.7.14，scons 3.0， VS2017 Pro

我的编译命令就是按照主页说的直接：scons

**Comment by xianjimli** [comment]
居然找不到stdio.h！感觉是VS没安装好，是不是什么SDK没有安装？
