### ISSUE TITLE
嵌入式linux下DRM接口与EGL接口性能差异

### ISSUE THREAD

**Issue by zjm1060** [zlgopen/awtk#535]
在嵌入式linux下使用DRM接口或者FB接口跑demo平均可以跑到55fps，使用EGL接口开启GPU硬件加速只能跑到10fps
使用https://github.com/zlgopen/awtk-linux-fb项目做的测试，硬件平台stm32mp157C-DK2，
发现大量的时间消耗在vgcanvas_nanovg_end_frame这个函数中

**Comment by WNsACE** [comment]
这个问题本质是因为 nanovg 的性能比较差导致的，我们最近也在在研究解决方案，需要一些时间优化。
