### ISSUE TITLE
最新源码报错，编译不过

### ISSUE THREAD

**Issue by WeSrc-Yin** [zlgopen/awtk#545]
src/hal/tools/network_shell/network_shell.c:31:30: fatal error: readline/history.h: No such file or directory
 #include <readline/history.h>
                              ^
compilation terminated.
scons: *** [src/hal/tools/network_shell/network_shell.o] Error 1
scons: building terminated because of errors.

commit 4a4217eba337ccb4a9b18db1c6c85b8d45a19953

**Comment by xianjimli** [comment]
看看是不是这个问题：https://github.com/zlgopen/awtk/issues/541

**Comment by WeSrc-Yin** [comment]
> 看看是不是这个问题：#541

是这个问题，安装libreadline-dev就可以了，多谢！
