### ISSUE TITLE
目前的代码运行show_fps后，在我的嵌入式linux屏上会在FPS下方显示很多条纹，前几天的代码是没有这个问题的

### ISSUE THREAD

**Issue by liusha0002000** [zlgopen/awtk#55]

**Comment by xianjimli** [comment]
板子在办公室，下周我看看。

**Comment by xianjimli** [comment]
我这里用demoui跑没问题。上张截图看看。

**Comment by liusha0002000** [comment]
![fps_error](https://user-images.githubusercontent.com/14558421/49497976-a288cf00-f8a4-11e8-8b5b-5ea08b5ea136.jpg)
