### ISSUE TITLE
应用程序初始化相关问题

### ISSUE THREAD

**Issue by zxc3489** [zlgopen/awtk#550]
在我们的板子上，ui程序从运行(此时整个界面显示为白色)到加载数据到应用程序待ui展示出来,大概有4秒钟时间，整个期间，界面都是纯白待。是否有途径将这个白色的界面去掉(启动时不去初始化lcd)，或者替换为自定待图片。

**Comment by zxc3489** [comment]
跑的是linux,有文件系统，awtk是去年十月份的代码

**Comment by xianjimli** [comment]
用最新版本试试，后来用mmap加载资源，应该快一些。
