### ISSUE TITLE
能否在Style样式里设置控件的feedback属性以开启按键音？

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk#554]
添加按钮的按键音时，发现要在代码里显式地设置控件的feedback属性才能开启其按键音。
如果能在Style样式里直接设置feedback属性，应该要方便很多。

**Comment by xianjimli** [comment]
我先看看。

**Comment by xianjimli** [comment]
修改了，feedback/focusable都可以在style里设置，你更新代码试试。谢谢

**Comment by ufbycd** [comment]
更新awtk代码后，awtk-mvvm编译就出错了(awtk-mvvm也更新了)：
`src/mvvm/awtk/binding_context_awtk.c: In function 'widget_trim_children':
src/mvvm/awtk/binding_context_awtk.c:474:9: error: 'widget_t' {aka 'struct _widget_t'} has no member named 'need_relayout_children'
   widget->need_relayout_children = TRUE;
         ^~
scons: *** [src/mvvm/awtk/binding_context_awtk.os] Error 1
scons: building terminated because of errors.
`

**Comment by ufbycd** [comment]
我尝试下删除这句话`widget->need_relayout_children = TRUE;`就编译通过了。
目前feedback style生效了。

**Comment by xianjimli** [comment]
awtk-mvvm也要更新一下。
