### ISSUE TITLE
rlottie widget for Toolkit AnyWhere

### ISSUE THREAD

**Issue by ajsb85** [zlgopen/awtk#558]
Allows to use rlottie animations in Toolkit AnyWhere

You can use [Samsung/rlottie](https://github.com/Samsung/rlottie) library with C-api header

Best regards.

Ref:
https://github.com/Samsung/rlottie/issues/484

**Comment by xianjimli** [comment]
OK, thanks.

**Comment by ajsb85** [comment]
Dear @xianjimli 

To download the UI Designer is very difficult to me because I have no Chinese nor Asian phone number.
Baidu or the AWTK云平台 needs as mandatory those numbers.

Can you send to me by Wetransfer maybe?

a.salas@ieee.org

Regards.

**Comment by soyzhc** [comment]
@ajsb85 

You can use a international mobile number to register an account with awtk.zlg.cn.
Select the mobile area code in the first registration step.

Please try again. and let me know if there is any exception during the registration process.

**Comment by ajsb85** [comment]
I can record the video of my frustrations
After several try to get the SMS finally the platform says that they can activate the account

My phone number: +34697703290
My email: alexander.salas@gmail.com

**Comment by soyzhc** [comment]
I'll have my colleagues in charge follow up on this next working day

**Comment by xianjimli** [comment]
Lottie works on AWTK now：https://github.com/zlgopen/awtk-widget-rlottie

**Comment by ajsb85** [comment]
Wow!

Very impressive. Kudos to you @xianjimli 

Help me to get the GUI Editor and the Evaluation board.
To start helping you!

Which one is the best evaluation board?
Maybe this?

![image](https://user-images.githubusercontent.com/663460/120878808-1cf25100-c5bf-11eb-98dc-bcbca121b95b.png)

https://it.aliexpress.com/item/1005001794778646.html?spm=a2g0o.cart.0.0.6cc53c00OqoSrY&mp=1

**Comment by ajsb85** [comment]
Hi, @soyzhc 

I am enrolled finally 😃 

![image](https://user-images.githubusercontent.com/663460/120880718-42398c00-c5cc-11eb-8343-08ffac946623.png)

**Comment by xianjimli** [comment]
😃
