### ISSUE TITLE
Rive: Create and ship interactive animations to any platform.

### ISSUE THREAD

**Issue by ajsb85** [zlgopen/awtk#562]
Dear @xianjimli 

Do you know about the Rive App?

Take a look this example by @jctoon 

This is an example of a state machine that you can use in Android, because the Rive Android runtime now supports state machines. #Bones #Icons #Characters #Android #StateMachine

https://rive.app/community/223-426-android-fun/

References:

https://github.com/rive-app/rive-cpp
https://github.com/rive-app/rive-tizen
https://github.com/rive-app/rive-lottie
https://github.com/zlgopen/awtk-android

**Comment by xianjimli** [comment]
Ok, thank you. It’s too busy lately, I will look at it this weekend.

**Comment by xianjimli** [comment]
AWTK rive player : https://github.com/zlgopen/awtk-widget-rive

**Comment by ajsb85** [comment]
Good job @xianjimli 
Could you add the license headers in the repository?
I shared the repository with the community on Twitter
https://twitter.com/ajsb85/status/1411794785006989315

**Comment by xianjimli** [comment]
Thank you. license is added.
