### ISSUE TITLE
正常的拼音输入导致程序崩溃

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk#563]
当我想在`edit`控件连写输入`你是谁`这三个汉字，而当拼音输入到`nishi`后再输入`s`就会使程序崩溃。崩溃时输出调试信息如下：
```
demo: 3rd/gpinyin/src/matrixsearch.cpp:1427：unsigned int ime_pinyin::MatrixSearch::get_lpis(const uint16*, unsigned int, ime_pinyin::LmaPsbItem*, unsigned int, const char16*, bool): 假设 ‘remain_num > 0’ 失败。
```
是一个断言失败。

经多次测试发现，输入到`nishi`后，只有再输入`s`才会崩溃，其它字母则不会。目前测试了x86_64 linux 跟arm linux平台，表现都一样。

**Comment by xianjimli** [comment]
Google PinYin输入法的问题。我也没看太懂，大概是用一个概率更大的选项替换前一个，不要那个assert也可以。你更新代码试试。谢谢。

**Comment by ufbycd** [comment]
嗯，可以了。
