### ISSUE TITLE
edit中input_type设置password,调用edit_set_text_limit，总是可见

### ISSUE THREAD

**Issue by wodingdong** [zlgopen/awtk#569]
在使用edit时，设置input_type为password，在逻辑处理中使用edit_set_text_limit，编译运行后，edit中的字符总是可见。
```
if (tk_str_eq(name, "edit_pwd"))
        {
            // set max and min char
            edit_set_text_limit(widget, PWD_MIN, PWD_MAX);
            widget_on(widget, EVT_VALUE_CHANGING, on_edit_pwd, win);
        }
```

![image](https://user-images.githubusercontent.com/16595552/123575514-88b58b80-d804-11eb-817c-dd3ee3156f4b.png)

是我使用的方式不对吗，不过正常逻辑设置edit的字符限制不会对可见性在影响。

**Comment by xianjimli** [comment]
在xml中用min/max属性设置。edit_set_text_limit同时会设置input_type为text。

**Comment by wodingdong** [comment]
希望在文档中标注清楚，谢谢
