### ISSUE TITLE
Keil AC6 编译错误

### ISSUE THREAD

**Issue by zaric00** [zlgopen/awtk#583]
![ac6](https://user-images.githubusercontent.com/58360577/127890132-9fb87132-3a69-4d2c-a13f-48bb54a55835.PNG)
基于rt1052-raw-master ，驱动使用最新SDK，编译器从AC5 切换为AC6，出现上图错误，如何解决？

**Comment by xianjimli** [comment]
参考这个文档试一下：https://github.com/zlgopen/awtk/blob/master/docs/how_to_build_with_keil_ac6.md

**Comment by zaric00** [comment]
已参考文档，进行修改，问题依旧。是否跟awtk_imx1050.lib有关？

**Comment by xianjimli** [comment]
那我不清楚，你问下ZLG的FAE。

**Comment by soyzhc** [comment]
已经添加v6工程支持

https://github.com/zlgopen/awtk-easyarm-rt1052-raw/tree/master/boards/easyarm-rt1052/awtk_examples/awtk_gui_demo/mdk_v6

**Comment by soyzhc** [comment]
@zaric00 请测试一下,如还不行请重开问题
