### ISSUE TITLE
显示gif图片时有残影，在ubuntu和嵌入式linux上都测试到了

### ISSUE THREAD

**Issue by liusha0002000** [zlgopen/awtk#59]
gif图片为：
[小黄鸭](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1543835076760&di=537cca1767cfa0ddfae05568937b3cc2&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fq_70%2Cc_zoom%2Cw_640%2Fimages%2F20180714%2F20410fd603b94d3fbf2ee1ff8f509cea.gif)
此gif中小黄鸭在跳下水前的状态在跳入水中后还有短暂显示，在PC上查看是没有的

**Comment by xianjimli** [comment]
可能是图片大小超出了控件大小，导致脏矩形计算出错。你用新的代码试试。

**Comment by liusha0002000** [comment]
新代码没问题了
