### ISSUE TITLE
ld: library not found for -lSDL2   when run scons on macOS  m1 

### ISSUE THREAD

**Issue by fanzhiri** [zlgopen/awtk#593]
with awtk so
scons: done reading SConscript files.
scons: Building targets ...
g++ -o bin/action_thread_test -framework IOKit -framework Cocoa -framework QuartzCore -framework OpenGL -weak_framework Metal -weak_framework MetalKit tests/action_thread_test.o -Llib -Lbin -lassets -limage_gen -ltheme_gen -lfont_gen -lstr_gen -lcommon -lawtk_global -lextwidgets -lwidgets -lbase -lgpinyin -lstreams -lconf_io -lhal -lcsv -lubjson -lcompressors -lfribidi -lmbedtls -lminiz -ltkc_static -llinebreak -lmbedtls -lnanovg -lSDL2 -lglad -lstdc++ -liconv -lpthread -lm -ldl
ld: library not found for -lSDL2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/action_thread_test] Error 1
scons: building terminated because of errors.

I have been installed the sdl2【sdl2: stable 2.0.16 (bottled), HEAD】

**Comment by fanzhiri** [comment]
> I don't know why, it works on my MacPro 2015.
需要编译一个arm64 的libSDL2.a，放到lib/libSDL2.a

**Comment by fanzhiri** [comment]
Undefined symbols for architecture arm64:
  "_AudioObjectAddPropertyListener", referenced from:
      _COREAUDIO_Init in libSDL2.a(SDL_coreaudio.o)
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectGetPropertyData", referenced from:
      _prepare_device in libSDL2.a(SDL_coreaudio.o)
      _assign_device_to_audioqueue in libSDL2.a(SDL_coreaudio.o)
      _device_unplugged in libSDL2.a(SDL_coreaudio.o)
      _build_device_list in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectGetPropertyDataSize", referenced from:
      _build_device_list in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectRemovePropertyListener", referenced from:
      _COREAUDIO_CloseDevice in libSDL2.a(SDL_coreaudio.o)
      _COREAUDIO_Deinitialize in libSDL2.a(SDL_coreaudio.o)
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueAllocateBuffer", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueDispose", referenced from:
      _COREAUDIO_CloseDevice in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueEnqueueBuffer", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
      _inputCallback in libSDL2.a(SDL_coreaudio.o)
      _outputCallback in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueNewInput", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueNewOutput", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueSetProperty", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
      _assign_device_to_audioqueue in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueStart", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_AudioQueueStop", referenced from:
      _audioqueue_thread in libSDL2.a(SDL_coreaudio.o)
  "_CHHapticDynamicParameterIDHapticIntensityControl", referenced from:
      -[SDL_RumbleMotor setIntensity:] in libSDL2.a(SDL_mfijoystick.o)
  "_CHHapticEventParameterIDHapticIntensity", referenced from:
      -[SDL_RumbleMotor setIntensity:] in libSDL2.a(SDL_mfijoystick.o)
  "_CHHapticEventTypeHapticContinuous", referenced from:
      -[SDL_RumbleMotor setIntensity:] in libSDL2.a(SDL_mfijoystick.o)
  "_FFCreateDevice", referenced from:
      _DARWIN_JoystickRumble in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceCreateEffect", referenced from:
      _DARWIN_JoystickRumble in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticNewEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceGetForceFeedbackCapabilities", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceGetForceFeedbackProperty", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceReleaseEffect", referenced from:
      _JoystickDeviceWasRemovedCallback in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticDestroyEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceSendForceFeedbackCommand", referenced from:
      _DARWIN_JoystickRumble in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticPause in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticUnpause in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticStopAll in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceSetForceFeedbackProperty", referenced from:
      _SDL_SYS_HapticSetGain in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticSetAutocenter in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectGetEffectStatus", referenced from:
      _SDL_SYS_HapticGetEffectStatus in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectSetParameters", referenced from:
      _DARWIN_JoystickRumble in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticUpdateEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectStart", referenced from:
      _DARWIN_JoystickRumble in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticRunEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectStop", referenced from:
      _SDL_SYS_HapticStopEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFIsForceFeedback", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_iokitjoystick.o)
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
  "_FFReleaseDevice", referenced from:
      _JoystickDeviceWasRemovedCallback in libSDL2.a(SDL_iokitjoystick.o)
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticClose in libSDL2.a(SDL_syshaptic.o)
  "_GCControllerDidConnectNotification", referenced from:
      _IOS_JoystickInit in libSDL2.a(SDL_mfijoystick.o)
      _IOS_JoystickQuit in libSDL2.a(SDL_mfijoystick.o)
  "_GCControllerDidDisconnectNotification", referenced from:
      _IOS_JoystickInit in libSDL2.a(SDL_mfijoystick.o)
      _IOS_JoystickQuit in libSDL2.a(SDL_mfijoystick.o)
  "_GCHapticDurationInfinite", referenced from:
      -[SDL_RumbleMotor setIntensity:] in libSDL2.a(SDL_mfijoystick.o)
  "_GCHapticsLocalityLeftHandle", referenced from:
      _IOS_JoystickInitRumble in libSDL2.a(SDL_mfijoystick.o)
  "_GCHapticsLocalityLeftTrigger", referenced from:
      _IOS_JoystickInitRumble in libSDL2.a(SDL_mfijoystick.o)
  "_GCHapticsLocalityRightHandle", referenced from:
      _IOS_JoystickInitRumble in libSDL2.a(SDL_mfijoystick.o)
  "_GCHapticsLocalityRightTrigger", referenced from:
      _IOS_JoystickInitRumble in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputDualShockTouchpadButton", referenced from:
      _IOS_AddJoystickDevice in libSDL2.a(SDL_mfijoystick.o)
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputDualShockTouchpadOne", referenced from:
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputDualShockTouchpadTwo", referenced from:
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputXboxPaddleFour", referenced from:
      _IOS_AddJoystickDevice in libSDL2.a(SDL_mfijoystick.o)
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputXboxPaddleOne", referenced from:
      _IOS_AddJoystickDevice in libSDL2.a(SDL_mfijoystick.o)
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputXboxPaddleThree", referenced from:
      _IOS_AddJoystickDevice in libSDL2.a(SDL_mfijoystick.o)
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_GCInputXboxPaddleTwo", referenced from:
      _IOS_AddJoystickDevice in libSDL2.a(SDL_mfijoystick.o)
      _IOS_MFIJoystickUpdate in libSDL2.a(SDL_mfijoystick.o)
  "_KBGetLayoutType", referenced from:
      _Cocoa_HandleKeyEvent in libSDL2.a(SDL_cocoakeyboard.o)
  "_LMGetKbdType", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
      _Cocoa_HandleKeyEvent in libSDL2.a(SDL_cocoakeyboard.o)
  "_OBJC_CLASS_$_CHHapticDynamicParameter", referenced from:
      objc-class-ref in libSDL2.a(SDL_mfijoystick.o)
  "_OBJC_CLASS_$_CHHapticEvent", referenced from:
      objc-class-ref in libSDL2.a(SDL_mfijoystick.o)
  "_OBJC_CLASS_$_CHHapticEventParameter", referenced from:
      objc-class-ref in libSDL2.a(SDL_mfijoystick.o)
  "_OBJC_CLASS_$_CHHapticPattern", referenced from:
      objc-class-ref in libSDL2.a(SDL_mfijoystick.o)
  "_OBJC_CLASS_$_GCColor", referenced from:
      objc-class-ref in libSDL2.a(SDL_mfijoystick.o)
  "_OBJC_CLASS_$_GCController", referenced from:
      objc-class-ref in libSDL2.a(SDL_mfijoystick.o)
  "_TISCopyCurrentKeyboardLayoutInputSource", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
  "_TISGetInputSourceProperty", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
  "_kTISPropertyUnicodeKeyLayoutData", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/app_conf_multi_threads] Error 1
scons: building terminated because of errors.

**Comment by xianjimli** [comment]
我用brew安装的。
```
brew install scons sdl2 node
```

你看你那里有下面的文件吗？

```
jim@lixianjings-MacBook-Pro /usr % ls -l /usr/local/lib/libSDL2.*
lrwxr-xr-x  1 jim  admin  37 11  6  2020 /usr/local/lib/libSDL2.a -> ../Cellar/sdl2/2.0.12_1/lib/libSDL2.a
lrwxr-xr-x  1 jim  admin  41 11  6  2020 /usr/local/lib/libSDL2.dylib -> ../Cellar/sdl2/2.0.12_1/lib/libSDL2.dylib
```

**Comment by fanzhiri** [comment]
> 我用brew安装的。
> 
> ```
> brew install scons sdl2 node
> ```
> 
> 你看你那里有下面的文件吗？
> 
> ```
> jim@lixianjings-MacBook-Pro /usr % ls -l /usr/local/lib/libSDL2.*
> lrwxr-xr-x  1 jim  admin  37 11  6  2020 /usr/local/lib/libSDL2.a -> ../Cellar/sdl2/2.0.12_1/lib/libSDL2.a
> lrwxr-xr-x  1 jim  admin  41 11  6  2020 /usr/local/lib/libSDL2.dylib -> ../Cellar/sdl2/2.0.12_1/lib/libSDL2.dylib
> ```

fanzhiri@fanzhirideAir ~ %  lipo -info /usr/local/lib/libSDL2.a 
Non-fat file: /usr/local/lib/libSDL2.a is architecture: arm64

fanzhiri@fanzhirideAir awtk % lipo -info /opt/homebrew/lib/libSDL2.a
Non-fat file: /opt/homebrew/lib/libSDL2.a is architecture: arm64

**Comment by xianjimli** [comment]
我把/usr/local/lib加入到了LIBPATH中，你更新AWTK试试，谢谢。

**Comment by fanzhiri** [comment]
> 我把/usr/local/lib加入到了LIBPATH中，你更新AWTK试试，谢谢。

刚刚更新awtk了，可以了，正常编译了，谢谢

**Comment by fanzhiri** [comment]
it's ok after update the latest code ，tks
