### ISSUE TITLE
edit长度问题

### ISSUE THREAD

**Issue by Sokyx** [zlgopen/awtk#597]
xml中设置了edit属性：max="6"，然后代码中输入超过6个数字，比如我输入10个'5'，虽然界面edit显示的是6个字符‘5’，但是如果使用widget_get_text_utf8获取edit的值，能获取到自己输入了10个5，这个有问题的吧，最多只能获取6个数字啊

**Comment by Sokyx** [comment]
补充一下：input_type是custom或者custom_password，另外如果设成int等等，会调出键盘，不想要键盘，键盘的xml我也没有，但是还是会呼出键盘

**Comment by Sokyx** [comment]
应该是：edit_is_valid_char_default函数中：
switch (edit->input_type) {
    case INPUT_ASCII:
    case INPUT_PHONE:
    case INPUT_EMAIL:
    case INPUT_TEXT:
    case INPUT_PASSWORD: {
      if (text->size >= edit->max) {
        ret = FALSE;
      }
    }
    default:
      break;
  }
不对custom做判断处理吗？

**Comment by xianjimli** [comment]
好的，谢谢，我看看。

**Comment by Sokyx** [comment]
> 好的，谢谢，我看看。

不客气，应该的，我这边先打了个补丁

**Comment by xianjimli** [comment]
你更新代码试试，谢谢。keyboard为空字符串时，可以阻止软键盘弹出。

**Comment by Sokyx** [comment]
好的好的
