### ISSUE TITLE
关于设置silde_view初始界面的设置

### ISSUE THREAD

**Issue by 18611429192** [zlgopen/awtk#598]
我想实现的东西是桌面有三个view 装在一个silde_view中，home_page在slide_view中第二页，但是我想让机器一开机就显示home_page而不是slide_view中的第一页，所以想用slide_indicator_set_indicated_target 这个函数在子控件初始化结束后将页面设置到home_page上，但是出现了问题，且不知道怎么结局，感觉官方文档对这些函数的描述太少了，摸不清楚怎么使用。
![image](https://user-images.githubusercontent.com/49744753/131773915-70150331-6652-4e41-8b14-91fa7f371230.png)
![image](https://user-images.githubusercontent.com/49744753/131773937-1d2e89e2-2bea-46a4-81d9-ac872487e20e.png)
![image](https://user-images.githubusercontent.com/49744753/131773955-ace2511e-a846-4cca-b972-4104cfa95c71.png)

**Comment by 18611429192** [comment]
使用slide_view_set_active会直接崩溃
![image](https://user-images.githubusercontent.com/49744753/131774640-ce22e845-0b07-4d99-b93e-58b9e73bb657.png)

**Comment by xianjimli** [comment]
你把窗口当slide_view使用了。先用widget_lookup查到slide_view，再调用slide_view_set_active。

**Comment by 18611429192** [comment]
明白了，感谢解答
