### ISSUE TITLE
什么时候能支持STM32F7xxx的芯片，驱动RGB屏，使用LTDC方式。。。。。

### ISSUE THREAD

**Issue by wpmyj** [zlgopen/awtk#6]
什么时候能支持STM32F7xxx的芯片，驱动RGB屏，使用LTDC方式。。。。。

**Comment by xianjimli** [comment]
下周我买块板子研究一下，最近比较忙，一个月之内吧:) 谢谢支持！

**Comment by xianjimli** [comment]
stm32f767igtx裸系统版本移植完成：https://github.com/zlgopen/awtk-stm32f767igtx-raw

**Comment by wpmyj** [comment]
有也野火的平台吗？你们ZLG的张波在野火群里聊得那么嗨，就是不见使用野火的平台。。。

**Comment by xianjimli** [comment]
很抱歉不能帮到你。开发板是我个人买的，因为以前有块正点原子的F429板子(底板+主板+屏)，只需要买块F767的主板就行了，如果你事先声明要野火的板子，我肯定会考虑买野火F767开发板的。
