### ISSUE TITLE
关于多语言中 combox控件的文本内容显示问题

### ISSUE THREAD

**Issue by jason-zhanghe** [zlgopen/awtk#603]
您好，在项目中使用awtk 多国语言显示的功能中遇到一个显示的小问题，在涉及到字符翻转处理的情况下，比如希伯来语
控件 combox  中下拉列表的内容与选定显示的内容相反，效果如下（部件属性默认）
![Dingtalk_20210910121605](https://user-images.githubusercontent.com/90435907/132799392-e5c87611-2862-4f05-958c-1ba2b6d4dae1.jpg)

**Comment by xianjimli** [comment]
好的，你更新awtk试试。谢谢

**Comment by jason-zhanghe** [comment]
测试没有问题了，谢谢

**Comment by xianjimli** [comment]
刚才那个版本有点问题，麻烦再更新一下。
