### ISSUE TITLE
HelloDesigner-Demo中widget的bar_timer_id属性没在手册和自定义属性中找到

### ISSUE THREAD

**Issue by Ttwus** [zlgopen/awtk#608]
李老师，你好我刚接触awtk，想请问一下在windows中编译的HelloDesigner-Demo，demo中关于window_basic这个窗口中创建的定时器同时配制了bar_timer_id属性，可我没有再没在手册和自定义属性中找到，请问这个属性是在哪定义的？

**Comment by xianjimli** [comment]
可能是自定义属性。只要属性名与内置的属性不冲突，你可以往widget里存放任何东西。
