### ISSUE TITLE
快速切换键盘窗口时有崩溃现象

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#61]
原因应该在这句代码
```
window_manager_check_if_need_open_animation()
  timer_add(on_idle_invalidate, curr_win, 100);   这句话有风险
```

这个timer即使是100ms, 也是有潜在风险的, 因为某些情况下窗口切换的速度可能
比100ms还快, 导致定时器到的时候, 实际窗口已经被销毁, 最终导致崩溃

可以将这100改为2000, 就很容易重现问题, 100的时候只是崩溃的概率小了

**Comment by soyzhc** [comment]
可以延伸检查一下awtk里面所有的timer_add是否安全, 定时器到的时候传递的对象是否能保证有效

**Comment by xianjimli** [comment]
已修改。谢谢。

**Comment by soyzhc** [comment]
74da63b82d6d3493a9015e4f40d490d00bcf4e87
