### ISSUE TITLE
我用Valgrind 检测了下，发现有内存泄露问题

### ISSUE THREAD

**Issue by 18611429192** [zlgopen/awtk#616]
我用Valgrind 检测了下我的程序，发现有内存泄露问题
内存泄漏的地方，我不知道在哪，应该不是我自己的代码（根本就没几行是我的），用的都是awtk的api。
![image](https://user-images.githubusercontent.com/49744753/134807544-1faabc4e-3cf6-446c-b8b7-383e068696b5.png)
[日志在这里](https://github.com/18611429192/my_picture/blob/main/myleak.txt)
[awtk的log在这里](https://github.com/18611429192/my_picture/blob/main/awtk_out.txt)

**Comment by xianjimli** [comment]
SDL对valgrind不太友好，你让AWTK运行在FB模式上，再用valgrind测试。
参考：https://github.com/zlgopen/awtk-linux-fb/blob/master/docs/vmware_linux_fb.md

**Comment by 18611429192** [comment]
明白，有时间检查
