### ISSUE TITLE
关于控件 slide_view

### ISSUE THREAD

**Issue by ZIKEER** [zlgopen/awtk#626]
目前使用这个控件实现屏幕翻页，比如三个页面通过滑动切换页面 现在在第二个页面有个按钮按下后第二个页面保持住，滑动翻页不生效 ，再次按下后又可以滑动翻页，求解这种情况可以实现么？

**Comment by xianjimli** [comment]
感觉不是一个正常的需求。你描述一下为什么需要这样的功能，我再考虑是否加

**Comment by ZIKEER** [comment]
我在查看 ZLG AWTK 1.6 Release Notes 时发现了这一句话 EVT_VALUE_WILL_CHANGE 事件返回 RET_STOP 可以阻止修改值，
通过这个可以实现上面提到的需求
