### ISSUE TITLE
使用dispatch接口分发事件挂死问题

### ISSUE THREAD

**Issue by yang0311** [zlgopen/awtk#627]
使用dispatch接口给当前界面的一个button分发click事件打开一个dialog，出现挂死问题，报错如下：
abort dispatch because sub main loop

**Comment by xianjimli** [comment]
不能在后台线程直接分发事件。看看这个文档：https://github.com/zlgopen/awtk/blob/master/docs/how_to_non_gui_thread_operate_widget.md
