### ISSUE TITLE
tk_mutex_create will crash

### ISSUE THREAD

**Issue by fanzhiri** [zlgopen/awtk#629]
awtk/src/platforms/rtt/mutex.c
原因mutex->mutex = rt_mutex_create(NULL, 0);
是调用rt_mutex_create函数第一个参数不能给个NULL

复现方式
1、编译rt-thread的qemu-vexpress-a9 工程
参考
https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/application-note/setup/qemu/windows/an0006-qemu-windows
2、把awtk添加到该工程上
参考
https://gitee.com/slako/awtk_rtthread_pack

**Comment by xianjimli** [comment]
你更新一下AWTK试试，谢谢。

**Comment by fanzhiri** [comment]
> 你更新一下AWTK试试，谢谢。

试了，这个问题解决了
