### ISSUE TITLE
slide_menu 可以支持同时显示多于3个button?

### ISSUE THREAD

**Issue by YasirLiang** [zlgopen/awtk#63]
slide_menu能同时显示多于3个的button?

**Comment by YasirLiang** [comment]
建议作为扩展支持

**Comment by xianjimli** [comment]
好，先等一段时间。谢谢

**Comment by YasirLiang** [comment]
期待。
这里还有一个需求便是：slide_menu 支持动态的样式，滑动slide_menu的时候，其选项根据其相应的位置动态修改选项的样式。比如选项在最中间的样式是和其在两边的样式不同，在slide_menu上的每个元素在每一个位置上都有相应的样式，这样的话，个性化更强一点。或者说还有其他的方法来实现这种需求？

**Comment by xianjimli** [comment]
已支持同时显示多个子控件。谢谢。

样式可以这样做：在上面盖一层图片(sensitive=false)，图片中部的透明最大，alpha渐变到两边，让人感觉按钮离中心区域的越远越暗。

**Comment by YasirLiang** [comment]
好 谢谢
