### ISSUE TITLE
有没有类似安卓那样的通知栏控件呢？

### ISSUE THREAD

**Issue by 18611429192** [zlgopen/awtk#632]
如题，想使用这样的控件，不知道有没有合适的，没有的话，自定义控件的话，感觉有点难搞。

**Comment by xianjimli** [comment]
用overlay应该可以实现。

**Comment by 18611429192** [comment]
好的，我去试试。

**Comment by 18611429192** [comment]
我希望这个通知栏控件能够在使用的时候加载，不用了就直接释放掉。然后可以在全局任何一个界面进行下拉操作。
我使用overlay窗口的代码、slide_view的代码和gesture的代码，结合使用。写了一个新的控件，但是控件基于window_base，slide_view基于widget_t，我不知道我这么改的问题出现在哪里，现在新控件调用on_paint_self函数后没有显示内容在屏幕上，过一会程序就直接退出了，不知道这个东西应该怎么搞了。
[代码在这里](https://github.com/18611429192/awtk/tree/myinfoview2/src/ext_widgets/info_view2)
