### ISSUE TITLE
关于自定义控件的问题

### ISSUE THREAD

**Issue by 1725879835** [zlgopen/awtk#639]
为什么我编译好的自定义控件添加到工程中无法看到函数，只有register头文件的两个函数。不是只需要将3rd中的自定义控件的register头文件包含就可以了吗？还是我在编译自定义控件的时候缺少了什么步骤呢？

**Comment by 1725879835** [comment]
目前是这种情况：例如代码widget_t*tree_view_control_create(widget_t*widget)
直接使用tree_view_control_create(widget);编译通过
widget_t*widget=tree_view_control_create(widget);编译失败，显示警告：“初始化”:“widget_t *”与“int”的间接级别不同

**Comment by xianjimli** [comment]
include对应的头文件即可。

**Comment by 1725879835** [comment]
十分感谢
