### ISSUE TITLE
求教awtk在嵌入式linux中要怎么做才能支持触控

### ISSUE THREAD

**Issue by 1725879835** [zlgopen/awtk#674]
需要额外的步骤吗

**Comment by archeng504** [comment]
你的平台首先要支持触摸功能才行。然后，你需要下载tslib，并编译。tslib编译成功，要修改awtk-linux-fb中的awtk_config.py文件，添加tslib的相关路径 TSLIB_LIB_DIR 和 TSLIB_INC_DIR

**Comment by 1725879835** [comment]
十分感谢
