### ISSUE TITLE
求教想要在嵌入式linux上支持ARGB1555的颜色格式需要怎么做

### ISSUE THREAD

**Issue by 1725879835** [zlgopen/awtk#677]
如何添加一种新的格式并修改颜色格式，现在只看到designer中的项目主题设置里有设置颜色格式，如果想要在文件上修改需要更改哪些部分

**Comment by xianjimli** [comment]
参考：https://github.com/zlgopen/awtk-linux-fb/blob/master/awtk-port/lcd_linux/lcd_mem_others.c
