### ISSUE TITLE
窗口透明然后控件移动会留下残影

### ISSUE THREAD

**Issue by 1725879835** [zlgopen/awtk#679]
颜色格式为ARGB1555，在嵌入式linux上运行
定义了WITH_LCD_CLEAR_ALPHA 但是并没有用，该在哪里定义呢？

**Comment by WNsACE** [comment]
awtk 默认不支持 ARGB1555 格式的，所以需要使用  lcd_mem_special 作为桥接的，那你的 lcd_mem_special_create 的 fmt 参数是选择哪一个？
