### ISSUE TITLE
怎么实现多级菜单的功能

### ISSUE THREAD

**Issue by 18611429192** [zlgopen/awtk#684]
![image](https://user-images.githubusercontent.com/49744753/155498459-e0ccaa5d-4c01-4d3f-91e7-17af66597553.png)
如上图所示，想实现类似这样的多级菜单功能，不知道应该怎么实现？
翻找以前的[issues](https://github.com/zlgopen/awtk/issues/249)，发现awtk只支持一级菜单？现在能支持多级了么？

**Comment by xianjimli** [comment]
还不支持多级菜单。

**Comment by 18611429192** [comment]
好的，明白了
