### ISSUE TITLE
控件平移动画有残留片段

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk#697]
使用下方描述的控件平移动画：
```xml
<view name="detect_card" x="0" y="0" w="100%" h="100%">
	<image x="c" y="200" w="24" h="145" image="card"
		animation="y(from=200, to=100, duration=2000, repeat_times=0, delay=500)" />
	<label x="c" y="80%" w="200" h="50" tr_text="please insert a reagent card" />
</view>
```
在x86_64 Linux平台测试正常，但在ARM Linux平台出现残留的控件片段：
![Screenshot_20220306_165503](https://user-images.githubusercontent.com/2321526/156916206-277f665b-9079-48b0-8e57-b8bcd294c4b0.png)
x86_64 Linux平台正常

![IMG_20220306_123615](https://user-images.githubusercontent.com/2321526/156916234-c7458a01-fc9a-4599-98db-25814b102fee.jpg)
ARM Linux平台出现残留

**Comment by xianjimli** [comment]
麻烦更新AWTK试试。谢谢

**Comment by ufbycd** [comment]
嗯，问题解决了！Well done！
