### ISSUE TITLE
popup窗口弹出来的时候，后面的背景能不能颜色变暗一点？

### ISSUE THREAD

**Issue by wodingdong** [zlgopen/awtk#698]
如题
![1b300423e00cfcecbf9f0301def3d5a](https://user-images.githubusercontent.com/16595552/157023837-7c7ff640-6a41-4510-ae5e-d4fe50d9f4fb.png)

这样能保持popup弹出来在当前显眼的位置

**Comment by xianjimli** [comment]
看看这个文档，对popup也是有效的：https://github.com/zlgopen/awtk/blob/master/docs/dialog_highlight.md

**Comment by wodingdong** [comment]
非常感谢，这个有效果
