### ISSUE TITLE
您好，有演示视频吗，要不看不到你这个UI的具体情况

### ISSUE THREAD

**Issue by wpmyj** [zlgopen/awtk#7]
能否制作一些视频，给大家一个感官上的认识，要不看见代码，靠想象是不行的

**Comment by xianjimli** [comment]
基本控件演示：https://v.qq.com/x/page/n0781yla2vv.html

**Comment by xianjimli** [comment]
AWTK基本控件演示：https://v.qq.com/x/page/n0781yla2vv.html

**Comment by tomyqg** [comment]
李工好，视频里的事例程序在哪能下到啊？

**Comment by xianjimli** [comment]
就是demos目录下的demoui。
