### ISSUE TITLE
有没有人遇到 AWTK_designer 一直闪退的问题

### ISSUE THREAD

**Issue by suve7** [zlgopen/awtk#701]
1. 打开自己的项目，运行编辑一段时间后发现 AWTK_designer 占用的内存一直在增加，如果没注意，过一段时间后导致系统内存满，软件会崩溃闪退
2. 如果创建一个简单的项目，随便写几个控件，放一天都不会崩溃
3. 是不是有哪一些特殊的控件或者对某些控件做了特殊的设置 会导致工具内存泄漏？

**Comment by xuchaoze** [comment]
请问AWTK Designer是什么版本

**Comment by suve7** [comment]
1.1.4.0

**Comment by suve7** [comment]
官网重新下载了AWTK studio 没这个问题了

**Comment by xuchaoze** [comment]
1.1.4版本有内存泄露，后面的版本修复了。
