### ISSUE TITLE
freetype的支持

### ISSUE THREAD

**Issue by zjm1060** [zlgopen/awtk#71]
stb的库貌似对某些字体的支持不太好，我写了个free type的loader
[font_loader_freetype.zip](https://github.com/zlgopen/awtk/files/2709577/font_loader_freetype.zip)

**Comment by zjm1060** [comment]
内存占用有所增加，cpu时间有较大幅度降低

**Comment by xianjimli** [comment]
已合并，谢谢。

freetype是个好东西，就是有点大:)。

我做了一些调整，麻烦更新一下代码。

另外，destroy_glyph释放内存有点问题，麻烦有空看看。

**Comment by xianjimli** [comment]
## 计划将 AWTK 的开源协议切换到 Apache License 2.0

* AWTK 最初采用 LGPL v2.1，初衷仅要求对 AWTK 本体代码的修改进行开源，无意限制商业使用。

* 后来发现 LGPL v2.1 商用并不友好。为打消开发者的顾虑，计划迁移至对商业更加友好的 Apache License 2.0。

* 如果您同意将您提交的代码贡献允许采用 Apache License 2.0，无需做任何操作；

* 如果您不希望自己过往贡献的代码跟随项目变更为 Apache License 2.0，请及时与我们取得联系，我们将做相应处理。

* 感谢您对 AWTK 项目的贡献。
