### ISSUE TITLE
event_init 怎么传递参数

### ISSUE THREAD

**Issue by archeng504** [zlgopen/awtk#716]
想用 widget_dispatch 传递事件到窗口，使用以下代码
uint32_t test_uu = 100;
event_t e = event_init(EVT_USER_START + 200, &test_uu); 
widget_dispatch(window_manager(), &e);

--------------------------------------------------
接收窗口中注册
 widget_on(win, EVT_USER_START + 200, OnUserEvent, win);
 
static ret_t OnUserEvent(void* ctx, event_t* e)
{
    log_debug("OnUserEvent type = %d , target = %d \n", e->type, (int)*((int *)e->target));
    return RET_OK;    
}
--------------------------------------------------
窗口能收到自定义事件，但是 target 打印是 0

**Comment by xianjimli** [comment]
target = %p

**Comment by archeng504** [comment]
> target = %p

没用，e->target 这个指针的值会被改掉
