### ISSUE TITLE
特殊字符不显示

### ISSUE THREAD

**Issue by liukunsdo2005** [zlgopen/awtk#751]
你好，我使用awtk designer 创建项目，在静态文本里面填写℃ 符号，但是界面上不显示，我在项目设置---主题---保留的字符里面也添加℃ 符号了，但还是不显示，请问是需要改哪里？

**Comment by xianjimli** [comment]
还要看字体本身里面是否有这个字符。

**Comment by liukunsdo2005** [comment]
怎么把特殊字符放进字体里面啊？

**Comment by xianjimli** [comment]
找个完整的字体，比如微软雅黑。

**Comment by liukunsdo2005** [comment]
万分感谢，可以显示了，谢谢！！！
