### ISSUE TITLE
软键盘上顶edit后，在system_bar再开软键盘，出现两个system_bar的问题

### ISSUE THREAD

**Issue by lzh545** [zlgopen/awtk#773]
1、在system_bar和window各放一个edit，edit打开同一个键盘
![1](https://user-images.githubusercontent.com/28924342/194693461-4bc1a4ad-0e41-472b-a5fd-581e29e1c92d.png)

2、先打开window上edit的软键盘，键盘高度高于edit的位置，将edit顶上去，然后关闭键盘
![2](https://user-images.githubusercontent.com/28924342/194693462-666a718f-2455-421e-b306-03ce84c385ad.png)

3、再打开system_bar上edit的软键盘，出现两个system_bar窗
![3](https://user-images.githubusercontent.com/28924342/194693466-17906e32-6a8e-4913-9cc9-7a8bf3b2b53c.png)

4、关闭软键盘，system_bar还是显示两个
![4](https://user-images.githubusercontent.com/28924342/194693468-c0b2c760-69eb-4396-9015-4fcd949b1f66.png)

**Comment by xianjimli** [comment]
改了，你更新AWTK试试，谢谢。
