### ISSUE TITLE
label 控件文字内容会超过控件本身的长度

### ISSUE THREAD

**Issue by archeng504** [zlgopen/awtk#774]
label 控件怎么限制文本显示的长度？实际使用文字内容会超出控件本身的长度

**Comment by xianjimli** [comment]
用hscroll_label代替label吧

**Comment by scp1011** [comment]
有个取巧的办法，WIDGET_PROP_LINE_WRAP设置为TRUE，同时控制好高度，超出的就不会显示出来了
