### ISSUE TITLE
list_view中list_item焦点显示会错误

### ISSUE THREAD

**Issue by archeng504** [zlgopen/awtk#777]
使用 KEYBOARD_3KEYS  容易测到，列表总共30个list_item，焦点在第1个list_item时，按key_up，第30个list_item会不可见。
![image](https://user-images.githubusercontent.com/13399581/195981169-efc02628-f63f-4c8b-ad84-f22115941517.png)

[list_view_test.zip](https://github.com/zlgopen/awtk/files/9791796/list_view_test.zip)

**Comment by xianjimli** [comment]
麻烦更新AWTK再试试，谢谢。

**Comment by archeng504** [comment]
更新了，编译了好几遍，发现问题还有

**Comment by archeng504** [comment]
可以了
