### ISSUE TITLE
awtk windows模拟器是否可以自定义标题栏?

### ISSUE THREAD

**Issue by shiweiping** [zlgopen/awtk#789]
目前在windows上运行效果很棒，想定制标题栏,不知道如何实现.

**Comment by shiweiping** [comment]
我是想隐藏标题栏,自己实现标题栏,否则标题栏跟我的客户区格格不入,而且不同的系统标题栏样式/颜色也会不一样.

**Comment by shiweiping** [comment]
看市面上大部分GUI库都不支持, 如果AWTK可以支持的话那么必然可以提升竞争力，自己实现还是挺麻烦的,
实现思路：处理WM_NCHITTEST消息,配合SDL_SetWindowHitTest就可以在应用层自定义标题栏上的按钮等等.

**Comment by xianjimli** [comment]
主要是拖动和Resize不好处理。你在什么平台运行

**Comment by shiweiping** [comment]
windows平台，拖动和Resize,我已经实现了,过几天我把代码整理下同步补丁给你们.

**Comment by xianjimli** [comment]
不同平台(Windows/Linux/MacOS)，SDL消息处理行为不同，同样的代码，有的平台会出现消息死循环，Resize时狂闪。
