### ISSUE TITLE
用valgrind检查发现以下内存泄漏

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk#799]
用valgrind检查发现以下内存泄漏，不知道如何分析定位：

![图片](https://user-images.githubusercontent.com/64031915/208577206-4e46ee88-2322-46c9-accd-73397129e14f.png)

![图片](https://user-images.githubusercontent.com/64031915/208578146-2b9c73fa-2ebe-4a63-8d42-8fcb2917b546.png)

**Comment by RainMic1019** [comment]
第一块是解析的字模缓存，正常退出程序时会自动销毁，这个不用管。
第二块是 awtk-mvvm 那边的内存泄露，我们这边后面会看看。

**Comment by zhaoyangxia1990** [comment]
还有个现象就是，有两个窗体A、B都绑定了不同的view model，然后从窗体A之上打开窗体B，再关闭窗体B，如此反复操作，发现内存一直在往上增，知道内存耗尽，程序跑不动。反复确认过应用程序没有内存泄漏，而且窗体B绑定mvvm的控件越多，内存耗尽的越快。

感谢！

**Comment by aawuuu** [comment]
新版本的awtk已经解决了这个问题，你可以更新一下awtk与awtk-mvvm后试试

**Comment by zhaoyangxia1990** [comment]
OK，感谢！
