### ISSUE TITLE
在事件处理函数中调用widget_destroy(父控件)引起的问题

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#80]
比如一个view中包含一个button，在button的EVT_CLICK的事件处理函数中widget_destroy(view)，程序会有异常。

原因：
widget_on_pointer_up()在分发button的EVT_CLICK的事件后，会继续使用widget_find_target()查找button上是否有子控件需要分布事件，但在该widget_find_target()中的widget_to_local()会访问button的父控件view，由于view已销毁，故此时是野指针。

解决（有两种方式）：
1、在button的EVT_CLICK的事件处理函数中使用idle_add()延迟销毁view。建议AWTK直接提供一个延迟widget_destroy的接口。
2、widget_destroy_children()的时候应该断开父子之间的联系，比如在widget_do_destroy()时先widget->parent = NULL。

**Comment by xianjimli** [comment]
已修改。谢谢。

**Comment by soyzhc** [comment]
b6a11968daf816a70c1b576f3d1f8caa9c52fddf
