### ISSUE TITLE
change title

### ISSUE THREAD

**Issue by thile723** [zlgopen/awtk#809]
![image](https://user-images.githubusercontent.com/82926718/215317383-606a8df5-a94a-4edf-a7f2-f31968d84bc0.png)
Hello!
Can i add some words in title of app? Example the above image, can i change "awtk" word?
Thank!

**Comment by xianjimli** [comment]
define APP_NAME before including awtk_main.inc.

please refer this doc: https://github.com/zlgopen/awtk/blob/master/docs/awtk_main.md

**Comment by thile723** [comment]
i found it and changed successful, thank you very much!
