### ISSUE TITLE
svg demo behavior diff between win and ubuntu(SVG在WIN上demo异常)

### ISSUE THREAD

**Issue by jasonbu** [zlgopen/awtk#81]
start with windows
![win_start](https://user-images.githubusercontent.com/6532028/51519173-2863d800-1e5b-11e9-80aa-13172b260fbe.png)
process with windows
![win_processing](https://user-images.githubusercontent.com/6532028/51519175-2b5ec880-1e5b-11e9-9f86-c9b2736396b6.png)
process with ubuntu
![ubuntu_processing](https://user-images.githubusercontent.com/6532028/51519179-2dc12280-1e5b-11e9-9983-1c7138409fbc.png)
SVG demo run on win, lost some details.
SVG demo在windows运行的时候细节丢失.

**Comment by xianjimli** [comment]
请参考FAQ第五条：https://github.com/zlgopen/awtk/blob/master/docs/faq.md

**Comment by jasonbu** [comment]
```
#NANOVG_BACKEND='GL3'
#NANOVG_BACKEND='GLES2'
#NANOVG_BACKEND='GLES3'
NANOVG_BACKEND='AGG'
#NANOVG_BACKEND='AGGE'
#NANOVG_BACKEND='BGFX'
```
更新SConstruct之后问题解决
