### ISSUE TITLE
bin大小变为0的问题

### ISSUE THREAD

**Issue by lvehe** [zlgopen/awtk#814]
有时候偶然断电，再重新上电的时候，出现白屏的现象，从awtk提示来看，发现是界面的bin文件大小变为0。有时候是字库的bin文件，有时候字库、界面的bin文件均变为0。
我的疑问是：awtk对资源文件，比如bin文件，按理应该只是只读。即使出现突然断电的情况，bin文件应该不会突然变成0，应该还是保持原样。是不是Awtk退出的时候必须显式调用某资源释放函数才能保证资源文件的正常？？？

**Comment by xianjimli** [comment]
什么系统？资源是只读的，AWTK不会修改，可能是文件系统的问题。

**Comment by lvehe** [comment]
断电的时候，因为Linux还没有来得及sync更新文件系统，容易造成文件丢失或大小为0。如果突然断电，可能真的没有好的解决方法。只能上电的程序进行判断重新解压缩资源文件。
