### ISSUE TITLE
Duplicate assignment in tests/object_date_time_test.cc

### ISSUE THREAD

**Issue by szsam** [zlgopen/awtk#828]
https://github.com/zlgopen/awtk/blob/f534853b32907572a790cb29a19c09e49ced8d13/tests/object_date_time_test.cc#L22
Is there any specific reason for this? If not, please fix this typo...

**Comment by xianjimli** [comment]
写错了，已修改。谢谢。

**Comment by szsam** [comment]
Fixed in 8769c0546605087f83dcbd2337ee81918294e602
