### ISSUE TITLE
Integer overflow when calculating malloc() size

### ISSUE THREAD

**Issue by szsam** [zlgopen/awtk#835]
https://github.com/zlgopen/awtk/blob/f534853b32907572a790cb29a19c09e49ced8d13/tools/image_resize/resize.c#L27-L28
Variables `ow` and `oh` come from user input. If they are large enough, the multiplication to calculate malloc() size might overflow.

Possible fix:
``` C
if ((oh != 0 && ow > INT_MAX / oh) || (n != 0 && ow * oh > INT_MAX / n)) {
    odata = NULL;
} else {
    odata = (unsigned char*)malloc(ow * oh * n); 
}
if (odata != NULL) { 
    ...
}
```

**Comment by xianjimli** [comment]
已修改，谢谢。
