### ISSUE TITLE
image_animation控件播放长时间动画的需求

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#85]
要做一个开机动画，类似视频播放器，播放大概300张图片
目前的image_animation控件无法填入太多的图片序列

1、播放的图片达到上百张（比如img000.png ~ img150.png），控件不适用，建议提供以下接口：设置起始索引、结束索引、以及索引的formater；

2、可设置播放一帧图片后是否自动unref图片资源。

**Comment by xianjimli** [comment]
好，谢谢。我想想

**Comment by xianjimli** [comment]
已修改。谢谢

**Comment by soyzhc** [comment]
已测试，有几个需求不太满足，建议：
1、可在xml的属性中设置播完一帧图片自动unref释放
2、序列中如果有图片不存在，则保留显示上一帧图片
3、图片名字可以设置formater，这样文件名可以灵活定义

**Comment by xianjimli** [comment]
1和3已修改，2还是修改应用程序比较好，免得错误被掩盖。

**Comment by xianjimli** [comment]
2也改了。谢谢。

**Comment by soyzhc** [comment]
3639b00a01c4c95b14ac3b8fef7650e3fa7d8bf1
