### ISSUE TITLE
在对话框操作函数强转之前，建议加入assert检查widget类型

### ISSUE THREAD

**Issue by soyzhc** [zlgopen/awtk#87]
比如 dialog_quit()  这个函数
dialog_t* dialog = DIALOG(widget);

直接强转有可能widget不是dialog_t类型，导致后续内存操作出错
建议加入 assert(dialog_cast(widget))，方便开发者快速定位问题

其他的控件操作函数也建议都加入这种判断

**Comment by xianjimli** [comment]
dialog已修改，其它的我再想想怎么搞。

**Comment by xianjimli** [comment]
已修改。目前只能在PC上使用。

**Comment by soyzhc** [comment]
辛苦李工了

检查了一下发现下面的结构没有初始化.parent成员, 不知道是不是问题
TK_DECL_VTABLE(list_view)
TK_DECL_VTABLE(list_view_h)

还有一个是 .parent 改为 .super 或 .super_class 好像更符合大部分语言的称呼, 无需采纳, 只是我个人感觉

**Comment by xianjimli** [comment]
好，谢谢。list_view/list_view_h改了。

是的，parent class和super class都可以，但我觉的parent更体现出直接的super class，先保持现状吧:)

https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)
