### ISSUE TITLE
Missing null check

### ISSUE THREAD

**Issue by szsam** [zlgopen/awtk#871]
The return values of the following functions should be checked against NULL.
https://github.com/zlgopen/awtk/blob/1d8140d3d61126deaa2a36ccefa14cfd4311b0a8/tests/assets_manager_test.cc#L366
https://github.com/zlgopen/awtk/blob/1d8140d3d61126deaa2a36ccefa14cfd4311b0a8/tests/conf_ubjson_test.cc#L82

**Comment by xianjimli** [comment]
已修改，谢谢。

**Comment by Machiry** [comment]
Hey @xianjimli ,

I am Aravind Machiry, an Assistant Professor at Purdue's ECE Department.

This pull request (along with several others) is the result of our ongoing research work (along with @szsam) to improve the security of open-source embedded projects.

We are doing a short (5-minute) survey to understand the use of static analysis tools in embedded projects.

It would greatly benefit our research if you could fill out this anonymous survey: https://purdue.ca1.qualtrics.com/jfe/form/SV_0OnXfr5plPe1QCa

Thank you,
Aravind

**Comment by xianjimli** [comment]
@Machiry OK, I finished the survey.
