### ISSUE TITLE
button 同时注册长按与短按事件时，长按事件打开一个 dialog，会执行一次短按事件

### ISSUE THREAD

**Issue by longyuwlz** [zlgopen/awtk#88]
对一个 button 同时注册长按与点击事件时，如果长按事件将打开一个 dialog 且在按钮中释放按键，会触发一次点击事件。 

 这个点击事件在 dialog_modal 中调用 main_loop_run 时捕获，由于这时 button_pointer_up_cleanup 并没有执行，此点击事件会被执行。

**Comment by xianjimli** [comment]
已修改。谢谢。
