### ISSUE TITLE
windows下使用libvlc+awtk播放视频

### ISSUE THREAD

**Issue by Sokyx** [zlgopen/awtk#890]
libvlc有一个libvlc_media_player_set_hwnd 函数，可以将视频指定到控件上，请问awtk有支持这种方式吗？如果不支持，那是不是必须要用mutable_image控件来实现？

**Comment by Sokyx** [comment]
已经用mutable_image初步实现了

**Comment by xianjimli** [comment]
好的。你可以参考这个：https://github.com/zlgopen/awtk-media-player
