### ISSUE TITLE
建议app_conf模块支持fallback机制以便于配置文件升级

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk#898]
目前app_conf模块只是在用户配置文件不存在时才将默认配置文件复制为用户配置文件。这样是不够的，如果软件升级时默认配置有更新，将难以处理。

应该像linux或Qt的Qstettings模块那样支持fallback：默认配置跟用户配置都可以读取，但用户配置的优先级高于默认配置，优先读取用户配置，当在用户配置上读取不到配置项时就读取默认配置文件，保存时只保存到用户配置文件。

这样软件升级时只需替换默认配置文件即可，用户配置也不会被覆盖。

**Comment by xianjimli** [comment]
谢谢建议，已修改，你更新代码试试。

**Comment by ufbycd** [comment]
李大侠动作好快！我今天初步验证了下，暂时没发现问题。明天再继续测试。
