### ISSUE TITLE
image_manager_get_bitmap获得的位图格式在PC和linux-fb机器上不一致

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk#906]
awtk编译设置是bgra8888， image_manager_get_bitmap()调用一张图片，出来的位图格式和编译设置一致，但是到了机器上出来却是rgba8888，导致逻辑不一致。

微信群问了下，直接叫我去改awtk-linux-fb的代码，我感觉不应该是代码的问题，问下有没有什么设置？

我查了文档, 感觉12.3 图片解码模块的内容和问题解决，然后配置了`#define WITH_BITMAP_BGRA 1`重新编译一样，发现还是同样的问题。

**Comment by xianjimli** [comment]
在src/image_loader/image_loader_stb.c里设置一个端点或者打印一些信息看看。
