### ISSUE TITLE
不同编译器对位域的实现是不同的，十分不建议在关键头文件中使用位域！

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk#918]
在用Zig调用AWTK时遇到了[zig不兼容位域的问题](https://github.com/zlgopen/awtk-mvvm/issues/64)。
后面查了下，原来是因为，C语言标准并没有规定位域的具体存储方式，不同的编译器有不同的实现。即位域的存储是非标准的，跨编译器使用会出现兼容性问题。

那主要的问题来了，AWTK的授权是LGPL，严格来说，商用情况下app只能动态链接awtk；有位域时，如果app的编译器跟库的编译器不同，则非常容易出现兼容性问题。

虽然大多数情况下，awtk库跟app都是使用相同的编译器。但严格来说，LGPL项目的主要头文件就不应该使用位域。

**Comment by xianjimli** [comment]
改了，你更新试试。我在做GO绑定也遇到位域不兼容的问题，改了一部分。

**Comment by ufbycd** [comment]
试下，没有暂时没发现问题。这样zig就可以直接调用AWTK了，方便太多。
