### ISSUE TITLE
digit_clock控件无法用C语言更改样式

### ISSUE THREAD

**Issue by erniuli** [zlgopen/awtk#92]
暂时无法通过C代码更改显示大小，颜色、字体等样式，期待后期加上。另外digit_clock format建议加上星期几的显示～

**Comment by xianjimli** [comment]
可以用主题设置啊。

**Comment by erniuli** [comment]
嗯嗯，已经通过修改相应的xml文件解决，感谢～

**Comment by xianjimli** [comment]
我加了星期和英文月份的支持。

https://github.com/zlgopen/awtk/blob/master/docs/manual/digit_clock_t.md#digit_clock_t_format

谢谢。
